/*
 * Generated by Tools/emojiOne.py on 2015-10-08.
 * You should not change this file manually.
 */

package org.telegram.messenger;

import java.util.HashMap;

public class EmojiData {
    public static long[][] data = {
        new long[]
            { //People, 144
                0xd83dde00L, 0xd83dde01L, 0xd83dde02L, 0xd83dde03L, 0xd83dde04L, 0xd83dde05L, 0xd83dde06L, 
                0xd83dde09L, 0xd83dde0aL, 0xd83dde0bL, 0xd83dde0eL, 0xd83dde0dL, 0xd83dde18L, 0xd83dde17L, 
                0xd83dde19L, 0xd83dde1aL, 0x263AL, 0xd83dde42L, 0xd83dde07L, 0xd83dde10L, 0xd83dde11L, 
                0xd83dde36L, 0xd83dde0fL, 0xd83dde23L, 0xd83dde25L, 0xd83dde2eL, 0xd83dde2fL, 0xd83dde2aL, 
                0xd83dde2bL, 0xd83dde34L, 0xd83dde0cL, 0xd83dde1bL, 0xd83dde1cL, 0xd83dde1dL, 0xd83dde41L, 
                0xd83dde12L, 0xd83dde13L, 0xd83dde14L, 0xd83dde15L, 0xd83dde16L, 0xd83dde37L, 0xd83dde32L, 
                0xd83dde1eL, 0xd83dde1fL, 0xd83dde24L, 0xd83dde22L, 0xd83dde2dL, 0xd83dde26L, 0xd83dde27L, 
                0xd83dde28L, 0xd83dde29L, 0xd83dde2cL, 0xd83dde30L, 0xd83dde31L, 0xd83dde33L, 0xd83dde35L, 
                0xd83dde21L, 0xd83dde20L, 0xd83ddc7fL, 0xd83dde08L, 0xd83ddc66L, 0xd83ddc67L, 0xd83ddc68L, 
                0xd83ddc69L, 0xd83ddc74L, 0xd83ddc75L, 0xd83ddc76L, 0xd83ddc71L, 0xd83ddc6eL, 0xd83ddc72L, 
                0xd83ddc73L, 0xd83ddc77L, 0xd83ddc78L, 0xd83ddc82L, 0xd83cdf85L, 0xd83ddc7cL, 0xd83ddd75L, 
                0xd83ddc6fL, 0xd83ddc86L, 0xd83ddc87L, 0xd83ddc70L, 0xd83dde4dL, 0xd83dde4eL, 0xd83dde45L, 
                0xd83dde46L, 0xd83ddc81L, 0xd83dde4bL, 0xd83dde47L, 0xd83dde4cL, 0xd83dde4fL, 0xd83ddde3L, 
                0xd83ddc64L, 0xd83ddc65L, 0xd83ddd74L, 0xd83ddc8fL, 0xd83ddc91L, 0xd83ddc6aL, 0xd83ddc6bL, 
                0xd83ddc6cL, 0xd83ddc6dL, 0xd83ddcaaL, 0xd83ddc48L, 0xd83ddc49L, 0x261DL, 0xd83ddc46L, 
                0xd83ddd95L, 0xd83ddc47L, 0x270CL, 0xd83ddd96L, 0xd83ddd90L, 0x270AL, 0x270BL, 
                0xd83ddc4aL, 0xd83ddc4cL, 0xd83ddc4dL, 0xd83ddc4eL, 0xd83ddc4bL, 0xd83ddc4fL, 0xd83ddc50L, 
                0xd83ddc85L, 0xd83ddc63L, 0xd83ddc40L, 0xd83ddc41L, 0xd83ddc42L, 0xd83ddc43L, 0xd83ddc45L, 
                0xd83ddc44L, 0xd83ddc8bL, 0xd83ddc79L, 0xd83ddc7aL, 0xd83ddc7bL, 0xd83ddc80L, 0xd83ddc7dL, 
                0xd83ddc7eL, 0xd83ddca9L, 0xd83dde38L, 0xd83dde39L, 0xd83dde3aL, 0xd83dde3bL, 0xd83dde3cL, 
                0xd83dde3dL, 0xd83dde3eL, 0xd83dde3fL, 0xd83dde40L                }
,         new long[]
            { //Nature, 131
                0xd83ddca7L, 0xd83ddca6L, 0xd83ddca8L, 0xd83ddc35L, 0xd83dde48L, 0xd83dde49L, 0xd83dde4aL, 
                0xd83ddc12L, 0xd83ddc36L, 0xd83ddc15L, 0xd83ddc29L, 0xd83ddc3aL, 0xd83ddc31L, 0xd83ddc08L, 
                0xd83ddc2fL, 0xd83ddc05L, 0xd83ddc06L, 0xd83ddc34L, 0xd83ddc0eL, 0xd83ddc2eL, 0xd83ddc02L, 
                0xd83ddc03L, 0xd83ddc04L, 0xd83ddc37L, 0xd83ddc16L, 0xd83ddc17L, 0xd83ddc3dL, 0xd83ddc0fL, 
                0xd83ddc11L, 0xd83ddc10L, 0xd83ddc2aL, 0xd83ddc2bL, 0xd83ddc18L, 0xd83ddc2dL, 0xd83ddc01L, 
                0xd83ddc00L, 0xd83ddc39L, 0xd83ddc30L, 0xd83ddc07L, 0xd83ddc3fL, 0xd83ddc3bL, 0xd83ddc28L, 
                0xd83ddc3cL, 0xd83ddc3eL, 0xd83ddc14L, 0xd83ddc13L, 0xd83ddc23L, 0xd83ddc24L, 0xd83ddc25L, 
                0xd83ddc26L, 0xd83ddc27L, 0xd83ddd4aL, 0xd83ddc38L, 0xd83ddc0aL, 0xd83ddc22L, 0xd83ddc0dL, 
                0xd83ddc32L, 0xd83ddc09L, 0xd83ddc33L, 0xd83ddc0bL, 0xd83ddc2cL, 0xd83ddc1fL, 0xd83ddc20L, 
                0xd83ddc21L, 0xd83ddc19L, 0xd83ddc1aL, 0xd83ddc0cL, 0xd83ddc1bL, 0xd83ddc1cL, 0xd83ddc1dL, 
                0xd83ddc1eL, 0xd83ddd77L, 0xd83ddd78L, 0xd83ddc90L, 0xd83cdf38L, 0xd83ddcaeL, 0xd83cdff5L, 
                0xd83cdf39L, 0xd83cdf3aL, 0xd83cdf3bL, 0xd83cdf3cL, 0xd83cdf37L, 0xd83cdf31L, 0xd83cdf32L, 
                0xd83cdf33L, 0xd83cdf34L, 0xd83cdf35L, 0xd83cdf3eL, 0xd83cdf3fL, 0xd83cdf40L, 0xd83cdf41L, 
                0xd83cdf42L, 0xd83cdf43L, 0xd83cdf0dL, 0xd83cdf0eL, 0xd83cdf0fL, 0xd83cdf10L, 0xd83cdfd4L, 
                0xd83cdf0bL, 0xd83dddfbL, 0xd83dddfeL, 0xd83cdf04L, 0xd83cdf05L, 0xd83cdf0aL, 0xd83cdf0cL, 
                0xd83cdf11L, 0xd83cdf12L, 0xd83cdf13L, 0xd83cdf14L, 0xd83cdf15L, 0xd83cdf16L, 0xd83cdf17L, 
                0xd83cdf18L, 0xd83cdf19L, 0xd83cdf1aL, 0xd83cdf1bL, 0xd83cdf1cL, 0x2600L, 0xd83cdf1dL, 
                0xd83cdf1eL, 0x2601L, 0x26C5L, 0xd83cdf28L, 0xd83cdf08L, 0x2614L, 0x2744L, 
                0xd83cdf1fL, 0xd83cdf20L, 0xd83ddd25L, 0x26A1L, 0x2B50L                }
,         new long[]
            { //Food & Drink, Celebration, Activity, 158
                0xd83cdf47L, 0xd83cdf48L, 0xd83cdf49L, 0xd83cdf4aL, 0xd83cdf4bL, 0xd83cdf4cL, 0xd83cdf4dL, 
                0xd83cdf4eL, 0xd83cdf4fL, 0xd83cdf50L, 0xd83cdf51L, 0xd83cdf52L, 0xd83cdf53L, 0xd83cdf45L, 
                0xd83cdf46L, 0xd83cdf3dL, 0xd83cdf36L, 0xd83cdf44L, 0xd83cdf30L, 0xd83cdf5eL, 0xd83cdf56L, 
                0xd83cdf57L, 0xd83cdf54L, 0xd83cdf5fL, 0xd83cdf55L, 0xd83cdf72L, 0xd83cdf71L, 0xd83cdf58L, 
                0xd83cdf59L, 0xd83cdf5aL, 0xd83cdf5bL, 0xd83cdf5cL, 0xd83cdf5dL, 0xd83cdf60L, 0xd83cdf62L, 
                0xd83cdf63L, 0xd83cdf64L, 0xd83cdf65L, 0xd83cdf61L, 0xd83cdf66L, 0xd83cdf67L, 0xd83cdf68L, 
                0xd83cdf69L, 0xd83cdf6aL, 0xd83cdf82L, 0xd83cdf70L, 0xd83cdf6bL, 0xd83cdf6cL, 0xd83cdf6dL, 
                0xd83cdf6eL, 0xd83cdf6fL, 0xd83cdf7cL, 0x2615L, 0xd83cdf75L, 0xd83cdf76L, 0xd83cdf77L, 
                0xd83cdf78L, 0xd83cdf79L, 0xd83cdf7aL, 0xd83cdf7bL, 0xd83cdf7dL, 0xd83cdf74L, 0xd83cdf73L, 
                0xd83ddc98L, 0x2764L, 0xd83ddc93L, 0xd83ddc94L, 0xd83ddc95L, 0xd83ddc96L, 0xd83ddc97L, 
                0xd83ddc99L, 0xd83ddc9aL, 0xd83ddc9bL, 0xd83ddc9cL, 0xd83ddc9dL, 0xd83ddc9eL, 0xd83ddc9fL, 
                0xd83ddc8cL, 0xd83ddca5L, 0xd83ddcabL, 0xd83ddc51L, 0xd83ddc8dL, 0xd83cdf82L, 0xd83cdf83L, 
                0xd83cdf84L, 0xd83cdf86L, 0xd83cdf87L, 0xd83cdf88L, 0xd83cdf89L, 0xd83cdf8aL, 0xd83cdf8bL, 
                0xd83cdf8cL, 0xd83cdf8dL, 0xd83cdf8eL, 0xd83cdf8fL, 0xd83cdf90L, 0xd83cdf91L, 0xd83cdf93L, 
                0xd83cdf80L, 0xd83cdf81L, 0xd83cdfeeL, 0xd83ddeb6L, 0xd83cdfc3L, 0xd83ddc83L, 0xd83cdfa9L, 
                0x26FAL, 0xd83cdfa0L, 0xd83cdfa1L, 0xd83cdfa2L, 0xd83cdfaaL, 0xd83cdfadL, 0xd83cdfa8L, 
                0xd83cdfb0L, 0xd83ddea3L, 0xd83ddec0L, 0x26C4L, 0xd83cdfafL, 0xd83cdfb4L, 0xd83cdfabL, 
                0x26BDL, 0x26BEL, 0xd83cdfc0L, 0xd83cdfc8L, 0xd83cdfc9L, 0xd83cdfbeL, 0xd83cdfb1L, 
                0xd83cdfb3L, 0x26F3L, 0xd83cdfccL, 0xd83cdfa3L, 0xd83cdfbdL, 0xd83cdfbfL, 0xd83cdfc2L, 
                0xd83cdfc4L, 0xd83cdfc7L, 0xd83cdfcaL, 0xd83cdfcbL, 0xd83ddeb4L, 0xd83ddeb5L, 0xd83cdfceL, 
                0xd83cdfcdL, 0xd83cdfc6L, 0xd83cdfaeL, 0xd83cdfb2L, 0xd83cdccfL, 0xd83cdc04L, 0xd83cdfbcL, 
                0xd83cdfb5L, 0xd83cdfb6L, 0xd83cdfa4L, 0xd83cdfa7L, 0xd83cdfb7L, 0xd83cdfb8L, 0xd83cdfb9L, 
                0xd83cdfbaL, 0xd83cdfbbL, 0xd83cdfacL, 0xd83cdfc1L                }
,         new long[]
            { //Travel & Places, Flags, 299
                0xd83cdfe0L, 0x26EAL, 0xd83cdfe2L, 0xd83cdfe3L, 0xd83cdfe4L, 0xd83cdfe5L, 0xd83cdfe6L, 
                0xd83cdfe8L, 0xd83cdfe9L, 0xd83cdfeaL, 0xd83cdfebL, 0xd83cdfecL, 0xd83cdfedL, 0xd83cdfefL, 
                0xd83cdff0L, 0xd83ddc92L, 0xd83dddfcL, 0xd83dddfdL, 0x26F2L, 0xd83cdf01L, 0xd83cdf03L, 
                0xd83cdf06L, 0xd83cdf07L, 0xd83cdf09L, 0xd83dddffL, 0xd83dde82L, 0xd83dde83L, 0xd83dde84L, 
                0xd83dde85L, 0xd83dde86L, 0xd83dde87L, 0xd83dde88L, 0xd83dde89L, 0xd83dde8aL, 0xd83dde9dL, 
                0xd83dde9eL, 0xd83dde8bL, 0xd83dde8cL, 0xd83dde8dL, 0xd83dde8eL, 0xd83dde8fL, 0xd83dde90L, 
                0xd83dde91L, 0xd83dde92L, 0xd83dde93L, 0xd83dde94L, 0xd83dde95L, 0xd83dde96L, 0xd83dde97L, 
                0xd83dde98L, 0xd83dde9aL, 0xd83dde9bL, 0xd83dde9cL, 0xd83ddeb2L, 0x26FDL, 0xd83ddee4L, 
                0xd83ddea8L, 0x2693L, 0x26F5L, 0xd83ddea3L, 0xd83ddea4L, 0xd83ddee5L, 0xd83ddea2L, 
                0x2708L, 0xd83ddcbaL, 0xd83dde81L, 0xd83dde9fL, 0xd83ddea0L, 0xd83ddea1L, 0xd83dde80L, 
                0xd83ddea5L, 0xd83ddea6L, 0xd83ddea7L, 0xd83ddec2L, 0xd83ddec3L, 0xd83ddec4L, 0xd83ddec5L, 
                0xd83ddcb4L, 0xd83ddcb5L, 0xd83ddcb6L, 0xd83ddcb7L, 0xd83cdde6d83cddebL, 0xd83cdde6d83cddf1L, 0xd83cdde9d83cddffL, 
                0xd83cdde6d83cdde9L, 0xd83cdde6d83cddf4L, 0xd83cdde6d83cddeeL, 0xd83cdde6d83cddecL, 0xd83cdde6d83cddf7L, 0xd83cdde6d83cddf2L, 0xd83cdde6d83cddfcL, 
                0xd83cdde6d83cdde8L, 0xd83cdde6d83cddfaL, 0xd83cdde6d83cddf9L, 0xd83cdde6d83cddffL, 0xd83cdde7d83cddf8L, 0xd83cdde7d83cddedL, 0xd83cdde7d83cdde9L, 
                0xd83cdde7d83cdde7L, 0xd83cdde7d83cddfeL, 0xd83cdde7d83cddeaL, 0xd83cdde7d83cddffL, 0xd83cdde7d83cddefL, 0xd83cdde7d83cddf2L, 0xd83cdde7d83cddf9L, 
                0xd83cdde7d83cddf4L, 0xd83cdde7d83cdde6L, 0xd83cdde7d83cddfcL, 0xd83cdde7d83cddf7L, 0xd83cdde7d83cddf3L, 0xd83cdde7d83cddecL, 0xd83cdde7d83cddebL, 
                0xd83cdde7d83cddeeL, 0xd83cddf0d83cddedL, 0xd83cdde8d83cddf2L, 0xd83cdde8d83cdde6L, 0xd83cdde8d83cddfbL, 0xd83cddf0d83cddfeL, 0xd83cdde8d83cddebL, 
                0xd83cddf9d83cdde9L, 0xd83cdde8d83cddf1L, 0xd83cdde8d83cddf3L, 0xd83cdde8d83cddf4L, 0xd83cddf0d83cddf2L, 0xd83cdde8d83cddecL, 0xd83cdde8d83cdde9L, 
                0xd83cdde8d83cddf7L, 0xd83cdde8d83cddeeL, 0xd83cddedd83cddf7L, 0xd83cdde8d83cddfaL, 0xd83cdde8d83cddfeL, 0xd83cdde8d83cddffL, 0xd83cdde9d83cddf0L, 
                0xd83cdde9d83cddefL, 0xd83cdde9d83cddf2L, 0xd83cdde9d83cddf4L, 0xd83cddead83cdde8L, 0xd83cddead83cddecL, 0xd83cddf8d83cddfbL, 0xd83cddecd83cddf6L, 
                0xd83cddead83cddf7L, 0xd83cddead83cddeaL, 0xd83cddead83cddf9L, 0xd83cddebd83cddf0L, 0xd83cddebd83cddf4L, 0xd83cddebd83cddefL, 0xd83cddebd83cddeeL, 
                0xd83cddebd83cddf7L, 0xd83cddf5d83cddebL, 0xd83cddecd83cdde6L, 0xd83cddecd83cddf2L, 0xd83cddecd83cddeaL, 0xd83cdde9d83cddeaL, 0xd83cddecd83cddedL, 
                0xd83cddecd83cddeeL, 0xd83cddecd83cddf7L, 0xd83cddecd83cddf1L, 0xd83cddecd83cdde9L, 0xd83cddecd83cddfaL, 0xd83cddecd83cddf9L, 0xd83cddecd83cddf3L, 
                0xd83cddecd83cddfcL, 0xd83cddecd83cddfeL, 0xd83cddedd83cddf9L, 0xd83cddedd83cddf3L, 0xd83cddedd83cddf0L, 0xd83cddedd83cddfaL, 0xd83cddeed83cddf8L, 
                0xd83cddeed83cddf3L, 0xd83cddeed83cdde9L, 0xd83cddeed83cddf7L, 0xd83cddeed83cddf6L, 0xd83cddeed83cddeaL, 0xd83cddeed83cddf1L, 0xd83cddeed83cddf9L, 
                0xd83cddefd83cddf2L, 0xd83cddefd83cddf5L, 0xd83cddefd83cddeaL, 0xd83cddefd83cddf4L, 0xd83cddf0d83cddffL, 0xd83cddf0d83cddeaL, 0xd83cddf0d83cddeeL, 
                0xd83cddfdd83cddf0L, 0xd83cddf0d83cddfcL, 0xd83cddf0d83cddecL, 0xd83cddf1d83cdde6L, 0xd83cddf1d83cddfbL, 0xd83cddf1d83cdde7L, 0xd83cddf1d83cddf8L, 
                0xd83cddf1d83cddf7L, 0xd83cddf1d83cddfeL, 0xd83cddf1d83cddeeL, 0xd83cddf1d83cddf9L, 0xd83cddf1d83cddfaL, 0xd83cddf2d83cddf4L, 0xd83cddf2d83cddf0L, 
                0xd83cddf2d83cddecL, 0xd83cddf2d83cddfcL, 0xd83cddf2d83cddfeL, 0xd83cddf2d83cddfbL, 0xd83cddf2d83cddf1L, 0xd83cddf2d83cddf9L, 0xd83cddf2d83cddedL, 
                0xd83cddf2d83cddf7L, 0xd83cddf2d83cddfaL, 0xd83cddf2d83cddfdL, 0xd83cddebd83cddf2L, 0xd83cddf2d83cdde9L, 0xd83cddf2d83cdde8L, 0xd83cddf2d83cddf3L, 
                0xd83cddf2d83cddeaL, 0xd83cddf2d83cddf8L, 0xd83cddf2d83cdde6L, 0xd83cddf2d83cddffL, 0xd83cddf2d83cddf2L, 0xd83cddf3d83cdde6L, 0xd83cddf3d83cddf7L, 
                0xd83cddf3d83cddf5L, 0xd83cddf3d83cddf1L, 0xd83cddf3d83cdde8L, 0xd83cddf3d83cddffL, 0xd83cddf3d83cddeeL, 0xd83cddf3d83cddeaL, 0xd83cddf3d83cddecL, 
                0xd83cddf3d83cddfaL, 0xd83cddf0d83cddf5L, 0xd83cddf3d83cddf4L, 0xd83cddf4d83cddf2L, 0xd83cddf5d83cddf0L, 0xd83cddf5d83cddfcL, 0xd83cddf5d83cddf8L, 
                0xd83cddf5d83cdde6L, 0xd83cddf5d83cddecL, 0xd83cddf5d83cddfeL, 0xd83cddf5d83cddeaL, 0xd83cddf5d83cddedL, 0xd83cddf5d83cddf1L, 0xd83cddf5d83cddf9L, 
                0xd83cddf5d83cddf7L, 0xd83cddf6d83cdde6L, 0xd83cddf7d83cddf4L, 0xd83cddf7d83cddfaL, 0xd83cddf7d83cddfcL, 0xd83cddfcd83cddf8L, 0xd83cddf8d83cddf2L, 
                0xd83cddf8d83cddf9L, 0xd83cddf8d83cdde6L, 0xd83cddf8d83cddf3L, 0xd83cddf7d83cddf8L, 0xd83cddf8d83cdde8L, 0xd83cddf8d83cddf1L, 0xd83cddf8d83cddecL, 
                0xd83cddf8d83cddf0L, 0xd83cddf8d83cddeeL, 0xd83cddf8d83cdde7L, 0xd83cddf8d83cddf4L, 0xd83cddffd83cdde6L, 0xd83cddf0d83cddf7L, 0xd83cddead83cddf8L, 
                0xd83cddf1d83cddf0L, 0xd83cddf8d83cddedL, 0xd83cddf0d83cddf3L, 0xd83cddf1d83cdde8L, 0xd83cddfbd83cdde8L, 0xd83cddf8d83cdde9L, 0xd83cddf8d83cddf7L, 
                0xd83cddf8d83cddffL, 0xd83cddf8d83cddeaL, 0xd83cdde8d83cddedL, 0xd83cddf8d83cddfeL, 0xd83cddf9d83cddfcL, 0xd83cddf9d83cddefL, 0xd83cddf9d83cddffL, 
                0xd83cddf9d83cddedL, 0xd83cddf9d83cddf1L, 0xd83cddf9d83cddecL, 0xd83cddf9d83cddf4L, 0xd83cddf9d83cddf9L, 0xd83cddf9d83cddf3L, 0xd83cddf9d83cddf7L, 
                0xd83cddf9d83cddf2L, 0xd83cddf9d83cddfbL, 0xd83cddfad83cddecL, 0xd83cddfad83cdde6L, 0xd83cdde6d83cddeaL, 0xd83cddecd83cdde7L, 0xd83cddfad83cddf8L, 
                0xd83cddfad83cddfeL, 0xd83cddfbd83cddeeL, 0xd83cddfad83cddffL, 0xd83cddfbd83cddfaL, 0xd83cddfbd83cdde6L, 0xd83cddfbd83cddeaL, 0xd83cddfbd83cddf3L, 
                0xd83cddfcd83cddebL, 0xd83cddead83cddedL, 0xd83cddfed83cddeaL, 0xd83cddffd83cddf2L, 0xd83cddffd83cddfcL                }
,         new long[]
            { //Objects & Symbols, 342
                0xd83ddca4L, 0xd83ddca2L, 0xd83ddca3L, 0xd83ddcacL, 0xd83ddcadL, 0xd83ddc53L, 0xd83ddc54L, 
                0xd83ddc55L, 0xd83ddc56L, 0xd83ddc57L, 0xd83ddc58L, 0xd83ddc59L, 0xd83ddc5aL, 0xd83ddc5bL, 
                0xd83ddc5cL, 0xd83ddc5dL, 0xd83ddecdL, 0xd83cdf92L, 0xd83ddc5eL, 0xd83ddc5fL, 0xd83ddc60L, 
                0xd83ddc61L, 0xd83ddc62L, 0xd83ddc52L, 0xd83ddc84L, 0xd83ddc8eL, 0xd83ddcaeL, 0x2668L, 
                0xd83ddc88L, 0xd83ddeb3L, 0xd83ddd31L, 0xd83cdfe7L, 0xd83ddeaeL, 0xd83ddeabL, 0xd83ddeadL, 
                0xd83ddeafL, 0xd83ddeb0L, 0xd83ddeb1L, 0xd83ddeb7L, 0xd83ddeb8L, 0x267FL, 0xd83ddeb9L, 
                0xd83ddebaL, 0xd83ddebbL, 0xd83ddebcL, 0xd83ddebeL, 0x26A0L, 0x26D4L, 0xd83ddeaaL, 
                0xd83ddebdL, 0xd83ddebfL, 0xd83ddec1L, 0x231BL, 0x23F3L, 0x231AL, 0x23F0L, 
                0xd83ddd5bL, 0xd83ddd67L, 0xd83ddd50L, 0xd83ddd5cL, 0xd83ddd51L, 0xd83ddd5dL, 0xd83ddd52L, 
                0xd83ddd5eL, 0xd83ddd53L, 0xd83ddd5fL, 0xd83ddd54L, 0xd83ddd60L, 0xd83ddd55L, 0xd83ddd61L, 
                0xd83ddd56L, 0xd83ddd62L, 0xd83ddd57L, 0xd83ddd63L, 0xd83ddd58L, 0xd83ddd64L, 0xd83ddd59L, 
                0xd83ddd65L, 0xd83ddd5aL, 0xd83ddd66L, 0x2648L, 0x2649L, 0x264AL, 0x264BL, 
                0x264CL, 0x264DL, 0x264EL, 0x264FL, 0x2650L, 0x2651L, 0x2652L, 
                0x2653L, 0x26CEL, 0xd83cdf00L, 0xd83cdf02L, 0x2660L, 0x2665L, 0x2666L, 
                0x2663L, 0xd83ddd07L, 0xd83ddd08L, 0xd83ddd09L, 0xd83ddd0aL, 0xd83ddce2L, 0xd83ddce3L, 
                0xd83ddcefL, 0xd83ddd14L, 0xd83ddd15L, 0xd83ddd00L, 0xd83ddd01L, 0xd83ddd02L, 0x25B6L, 
                0x23E9L, 0x25C0L, 0x23EAL, 0xd83ddd3cL, 0x23EBL, 0xd83ddd3dL, 0x23ECL, 
                0xd83ddcfbL, 0xd83ddcf1L, 0xd83ddcf3L, 0xd83ddcf4L, 0xd83ddcf2L, 0xd83ddcf5L, 0x260EL, 
                0xd83ddcdeL, 0x002320E3L, 0x003020E3L, 0x003120E3L, 0x003220E3L, 0x003320E3L, 0x003420E3L, 
                0x003520E3L, 0x003620E3L, 0x003720E3L, 0x003820E3L, 0x003920E3L, 0xd83ddd1fL, 0xd83ddcf6L, 
                0xd83ddcdfL, 0xd83ddce0L, 0xd83ddd0bL, 0xd83ddd0cL, 0xd83ddcbbL, 0xd83ddcbdL, 0xd83ddcbeL, 
                0xd83ddcbfL, 0xd83ddcc0L, 0xd83cdfa5L, 0xd83cdfa6L, 0xd83ddcfaL, 0xd83ddcf7L, 0xd83ddcfcL, 
                0xd83ddd05L, 0xd83ddd06L, 0xd83ddd0dL, 0xd83ddd0eL, 0xd83ddd2cL, 0xd83ddd2dL, 0xd83ddce1L, 
                0xd83ddca1L, 0xd83ddd26L, 0xd83ddcd4L, 0xd83ddcd5L, 0xd83ddcd6L, 0xd83ddcd7L, 0xd83ddcd8L, 
                0xd83ddcd9L, 0xd83ddcdaL, 0xd83ddcd3L, 0xd83ddcc3L, 0xd83ddcdcL, 0xd83ddcc4L, 0xd83ddcf0L, 
                0xd83ddcd1L, 0xd83ddd16L, 0xd83ddcb0L, 0xd83ddcb8L, 0xd83ddcb1L, 0xd83ddcb2L, 0xd83ddcb3L, 
                0xd83ddcb9L, 0x2709L, 0xd83ddce7L, 0xd83ddce8L, 0xd83ddce9L, 0xd83ddce4L, 0xd83ddce5L, 
                0xd83ddce6L, 0xd83ddcebL, 0xd83ddceaL, 0xd83ddcecL, 0xd83ddcedL, 0xd83ddceeL, 0x270FL, 
                0x2712L, 0xd83ddcddL, 0xd83ddcbcL, 0xd83ddcc1L, 0xd83ddcc2L, 0xd83ddcc5L, 0xd83ddcc6L, 
                0xd83ddcc7L, 0xd83ddcc8L, 0xd83ddcc9L, 0xd83ddccaL, 0xd83ddccbL, 0xd83ddcccL, 0xd83ddccdL, 
                0xd83ddcceL, 0xd83ddccfL, 0xd83ddcd0L, 0xd83ddcdbL, 0x2702L, 0xd83ddd12L, 0xd83ddd13L, 
                0xd83ddd0fL, 0xd83ddd10L, 0xd83ddd11L, 0xd83ddd28L, 0xd83ddd27L, 0xd83ddd29L, 0xd83ddd17L, 
                0xd83ddc89L, 0xd83ddc8aL, 0xd83ddd2aL, 0xd83ddd2bL, 0xd83ddeacL, 0xd83ddea9L, 0x2B06L, 
                0x2197L, 0x27A1L, 0x2198L, 0x2B07L, 0x2199L, 0x2B05L, 0x2196L, 
                0x2195L, 0x2194L, 0x21A9L, 0x21AAL, 0x2934L, 0x2935L, 0xd83ddd03L, 
                0xd83ddd04L, 0xd83ddd19L, 0xd83ddd1aL, 0xd83ddd1bL, 0xd83ddd1cL, 0xd83ddd1dL, 0xd83ddd30L, 
                0xd83ddd2eL, 0xd83ddd2fL, 0x267BL, 0x2B55L, 0x2705L, 0x2611L, 0x2714L, 
                0x2716L, 0x274CL, 0x274EL, 0x2795L, 0x2796L, 0x2797L, 0x27B0L, 
                0x27BFL, 0x303DL, 0x2733L, 0x2734L, 0x2747L, 0x203CL, 0x2049L, 
                0x2753L, 0x2754L, 0x2755L, 0x2757L, 0x00A9L, 0x00AEL, 0x2122L, 
                0xd83ddcafL, 0xd83ddd1eL, 0xd83ddd20L, 0xd83ddd21L, 0xd83ddd22L, 0xd83ddd23L, 0xd83ddd24L, 
                0xd83cdd70L, 0xd83cdd8eL, 0xd83cdd71L, 0xd83cdd91L, 0xd83cdd92L, 0xd83cdd93L, 0x2139L, 
                0xd83cdd94L, 0x24C2L, 0xd83cdd95L, 0xd83cdd96L, 0xd83cdd7eL, 0xd83cdd97L, 0xd83cdd7fL, 
                0xd83cdd98L, 0xd83cdd99L, 0xd83cdd9aL, 0xd83cde01L, 0xd83cde02L, 0xd83cde37L, 0xd83cde36L, 
                0xd83cde2fL, 0xd83cde50L, 0xd83cde39L, 0xd83cde1aL, 0xd83cde32L, 0xd83cde51L, 0xd83cde38L, 
                0xd83cde34L, 0xd83cde33L, 0x3297L, 0x3299L, 0xd83cde3aL, 0xd83cde35L, 0x25AAL, 
                0x25ABL, 0x25FBL, 0x25FCL, 0x25FDL, 0x25FEL, 0x2B1BL, 0x2B1CL, 
                0xd83ddd36L, 0xd83ddd37L, 0xd83ddd38L, 0xd83ddd39L, 0xd83ddd3aL, 0xd83ddd3bL, 0xd83ddca0L, 
                0xd83ddd32L, 0xd83ddd33L, 0x26AAL, 0x26ABL, 0xd83ddd34L, 0xd83ddd35L                }
    };
    public static final HashMap<Long, Integer[]> offsets;
    static{
        offsets = new HashMap<>();
        offsets.put(0xd83dde00L, new Integer[]{1984,704});
        offsets.put(0xd83dde01L, new Integer[]{1984,768});
        offsets.put(0xd83dde02L, new Integer[]{1984,832});
        offsets.put(0xd83dde03L, new Integer[]{1984,896});
        offsets.put(0xd83dde04L, new Integer[]{1984,960});
        offsets.put(0xd83dde05L, new Integer[]{1984,1024});
        offsets.put(0xd83dde06L, new Integer[]{1984,1088});
        offsets.put(0xd83dde09L, new Integer[]{1984,1280});
        offsets.put(0xd83dde0aL, new Integer[]{1984,1344});
        offsets.put(0xd83dde0bL, new Integer[]{1984,1408});
        offsets.put(0xd83dde0eL, new Integer[]{1984,1600});
        offsets.put(0xd83dde0dL, new Integer[]{1984,1536});
        offsets.put(0xd83dde18L, new Integer[]{256,1984});
        offsets.put(0xd83dde17L, new Integer[]{192,1984});
        offsets.put(0xd83dde19L, new Integer[]{320,1984});
        offsets.put(0xd83dde1aL, new Integer[]{384,1984});
        offsets.put(0x263AL, new Integer[]{2176,1728});
        offsets.put(0xd83dde42L, new Integer[]{2048,896});
        offsets.put(0xd83dde07L, new Integer[]{1984,1152});
        offsets.put(0xd83dde10L, new Integer[]{1984,1728});
        offsets.put(0xd83dde11L, new Integer[]{1984,1792});
        offsets.put(0xd83dde36L, new Integer[]{2048,128});
        offsets.put(0xd83dde0fL, new Integer[]{1984,1664});
        offsets.put(0xd83dde23L, new Integer[]{960,1984});
        offsets.put(0xd83dde25L, new Integer[]{1088,1984});
        offsets.put(0xd83dde2eL, new Integer[]{1664,1984});
        offsets.put(0xd83dde2fL, new Integer[]{1728,1984});
        offsets.put(0xd83dde2aL, new Integer[]{1408,1984});
        offsets.put(0xd83dde2bL, new Integer[]{1472,1984});
        offsets.put(0xd83dde34L, new Integer[]{2048,0});
        offsets.put(0xd83dde0cL, new Integer[]{1984,1472});
        offsets.put(0xd83dde1bL, new Integer[]{448,1984});
        offsets.put(0xd83dde1cL, new Integer[]{512,1984});
        offsets.put(0xd83dde1dL, new Integer[]{576,1984});
        offsets.put(0xd83dde41L, new Integer[]{2048,832});
        offsets.put(0xd83dde12L, new Integer[]{1984,1856});
        offsets.put(0xd83dde13L, new Integer[]{1984,1920});
        offsets.put(0xd83dde14L, new Integer[]{0,1984});
        offsets.put(0xd83dde15L, new Integer[]{64,1984});
        offsets.put(0xd83dde16L, new Integer[]{128,1984});
        offsets.put(0xd83dde37L, new Integer[]{2048,192});
        offsets.put(0xd83dde32L, new Integer[]{1920,1984});
        offsets.put(0xd83dde1eL, new Integer[]{640,1984});
        offsets.put(0xd83dde1fL, new Integer[]{704,1984});
        offsets.put(0xd83dde24L, new Integer[]{1024,1984});
        offsets.put(0xd83dde22L, new Integer[]{896,1984});
        offsets.put(0xd83dde2dL, new Integer[]{1600,1984});
        offsets.put(0xd83dde26L, new Integer[]{1152,1984});
        offsets.put(0xd83dde27L, new Integer[]{1216,1984});
        offsets.put(0xd83dde28L, new Integer[]{1280,1984});
        offsets.put(0xd83dde29L, new Integer[]{1344,1984});
        offsets.put(0xd83dde2cL, new Integer[]{1536,1984});
        offsets.put(0xd83dde30L, new Integer[]{1792,1984});
        offsets.put(0xd83dde31L, new Integer[]{1856,1984});
        offsets.put(0xd83dde33L, new Integer[]{1984,1984});
        offsets.put(0xd83dde35L, new Integer[]{2048,64});
        offsets.put(0xd83dde21L, new Integer[]{832,1984});
        offsets.put(0xd83dde20L, new Integer[]{768,1984});
        offsets.put(0xd83ddc7fL, new Integer[]{1600,1024});
        offsets.put(0xd83dde08L, new Integer[]{1984,1216});
        offsets.put(0xd83ddc66L, new Integer[]{1536,1408});
        offsets.put(0xd83ddc67L, new Integer[]{1536,1472});
        offsets.put(0xd83ddc68L, new Integer[]{704,1536});
        offsets.put(0xd83ddc69L, new Integer[]{1216,1536});
        offsets.put(0xd83ddc74L, new Integer[]{1600,320});
        offsets.put(0xd83ddc75L, new Integer[]{1600,384});
        offsets.put(0xd83ddc76L, new Integer[]{1600,448});
        offsets.put(0xd83ddc71L, new Integer[]{1600,128});
        offsets.put(0xd83ddc6eL, new Integer[]{1536,1536});
        offsets.put(0xd83ddc72L, new Integer[]{1600,192});
        offsets.put(0xd83ddc73L, new Integer[]{1600,256});
        offsets.put(0xd83ddc77L, new Integer[]{1600,512});
        offsets.put(0xd83ddc78L, new Integer[]{1600,576});
        offsets.put(0xd83ddc82L, new Integer[]{1600,1216});
        offsets.put(0xd83cdf85L, new Integer[]{384,1216});
        offsets.put(0xd83ddc7cL, new Integer[]{1600,832});
        offsets.put(0xd83ddd75L, new Integer[]{192,1856});
        offsets.put(0xd83ddc6fL, new Integer[]{1600,0});
        offsets.put(0xd83ddc86L, new Integer[]{1600,1472});
        offsets.put(0xd83ddc87L, new Integer[]{1600,1536});
        offsets.put(0xd83ddc70L, new Integer[]{1600,64});
        offsets.put(0xd83dde4dL, new Integer[]{2048,1472});
        offsets.put(0xd83dde4eL, new Integer[]{2048,1536});
        offsets.put(0xd83dde45L, new Integer[]{2048,960});
        offsets.put(0xd83dde46L, new Integer[]{2048,1024});
        offsets.put(0xd83ddc81L, new Integer[]{0,0});
        offsets.put(0xd83dde4bL, new Integer[]{2048,1344});
        offsets.put(0xd83dde47L, new Integer[]{2048,1088});
        offsets.put(0xd83dde4cL, new Integer[]{2048,1408});
        offsets.put(0xd83dde4fL, new Integer[]{2048,1600});
        offsets.put(0xd83ddde3L, new Integer[]{1216,1920});
        offsets.put(0xd83ddc64L, new Integer[]{1536,1280});
        offsets.put(0xd83ddc65L, new Integer[]{1536,1344});
        offsets.put(0xd83ddd74L, new Integer[]{128,1856});
        offsets.put(0xd83ddc8fL, new Integer[]{448,1600});
        offsets.put(0xd83ddc91L, new Integer[]{576,1600});
        offsets.put(0xd83ddc6aL, new Integer[]{1280,1536});
        offsets.put(0xd83ddc6bL, new Integer[]{1344,1536});
        offsets.put(0xd83ddc6cL, new Integer[]{1408,1536});
        offsets.put(0xd83ddc6dL, new Integer[]{1472,1536});
        offsets.put(0xd83ddcaaL, new Integer[]{1664,512});
        offsets.put(0xd83ddc48L, new Integer[]{1024,1472});
        offsets.put(0xd83ddc49L, new Integer[]{1088,1472});
        offsets.put(0x261DL, new Integer[]{2176,1664});
        offsets.put(0xd83ddc46L, new Integer[]{896,1472});
        offsets.put(0xd83ddd95L, new Integer[]{1920,0});
        offsets.put(0xd83ddc47L, new Integer[]{960,1472});
        offsets.put(0x270CL, new Integer[]{2240,64});
        offsets.put(0xd83ddd96L, new Integer[]{1920,64});
        offsets.put(0xd83ddd90L, new Integer[]{1600,1856});
        offsets.put(0x270AL, new Integer[]{2176,2176});
        offsets.put(0x270BL, new Integer[]{2240,0});
        offsets.put(0xd83ddc4aL, new Integer[]{1152,1472});
        offsets.put(0xd83ddc4cL, new Integer[]{1280,1472});
        offsets.put(0xd83ddc4dL, new Integer[]{1344,1472});
        offsets.put(0xd83ddc4eL, new Integer[]{1408,1472});
        offsets.put(0xd83ddc4bL, new Integer[]{1216,1472});
        offsets.put(0xd83ddc4fL, new Integer[]{1472,1472});
        offsets.put(0xd83ddc50L, new Integer[]{1536,0});
        offsets.put(0xd83ddc85L, new Integer[]{1600,1408});
        offsets.put(0xd83ddc63L, new Integer[]{1536,1216});
        offsets.put(0xd83ddc40L, new Integer[]{512,1472});
        offsets.put(0xd83ddc41L, new Integer[]{576,1472});
        offsets.put(0xd83ddc42L, new Integer[]{640,1472});
        offsets.put(0xd83ddc43L, new Integer[]{704,1472});
        offsets.put(0xd83ddc45L, new Integer[]{832,1472});
        offsets.put(0xd83ddc44L, new Integer[]{768,1472});
        offsets.put(0xd83ddc8bL, new Integer[]{192,1600});
        offsets.put(0xd83ddc79L, new Integer[]{1600,640});
        offsets.put(0xd83ddc7aL, new Integer[]{1600,704});
        offsets.put(0xd83ddc7bL, new Integer[]{1600,768});
        offsets.put(0xd83ddc80L, new Integer[]{1600,1088});
        offsets.put(0xd83ddc7dL, new Integer[]{1600,896});
        offsets.put(0xd83ddc7eL, new Integer[]{1600,960});
        offsets.put(0xd83ddca9L, new Integer[]{1664,448});
        offsets.put(0xd83dde38L, new Integer[]{2048,256});
        offsets.put(0xd83dde39L, new Integer[]{2048,320});
        offsets.put(0xd83dde3aL, new Integer[]{2048,384});
        offsets.put(0xd83dde3bL, new Integer[]{2048,448});
        offsets.put(0xd83dde3cL, new Integer[]{2048,512});
        offsets.put(0xd83dde3dL, new Integer[]{2048,576});
        offsets.put(0xd83dde3eL, new Integer[]{2048,640});
        offsets.put(0xd83dde3fL, new Integer[]{2048,704});
        offsets.put(0xd83dde40L, new Integer[]{2048,768});
        offsets.put(0xd83ddca7L, new Integer[]{1664,320});
        offsets.put(0xd83ddca6L, new Integer[]{1664,256});
        offsets.put(0xd83ddca8L, new Integer[]{1664,384});
        offsets.put(0xd83ddc35L, new Integer[]{1472,1280});
        offsets.put(0xd83dde48L, new Integer[]{2048,1152});
        offsets.put(0xd83dde49L, new Integer[]{2048,1216});
        offsets.put(0xd83dde4aL, new Integer[]{2048,1280});
        offsets.put(0xd83ddc12L, new Integer[]{512,1408});
        offsets.put(0xd83ddc36L, new Integer[]{1472,1344});
        offsets.put(0xd83ddc15L, new Integer[]{704,1408});
        offsets.put(0xd83ddc29L, new Integer[]{1472,512});
        offsets.put(0xd83ddc3aL, new Integer[]{128,1472});
        offsets.put(0xd83ddc31L, new Integer[]{1472,1024});
        offsets.put(0xd83ddc08L, new Integer[]{1408,1280});
        offsets.put(0xd83ddc2fL, new Integer[]{1472,896});
        offsets.put(0xd83ddc05L, new Integer[]{1408,1088});
        offsets.put(0xd83ddc06L, new Integer[]{1408,1152});
        offsets.put(0xd83ddc34L, new Integer[]{1472,1216});
        offsets.put(0xd83ddc0eL, new Integer[]{256,1408});
        offsets.put(0xd83ddc2eL, new Integer[]{1472,832});
        offsets.put(0xd83ddc02L, new Integer[]{1408,896});
        offsets.put(0xd83ddc03L, new Integer[]{1408,960});
        offsets.put(0xd83ddc04L, new Integer[]{1408,1024});
        offsets.put(0xd83ddc37L, new Integer[]{1472,1408});
        offsets.put(0xd83ddc16L, new Integer[]{768,1408});
        offsets.put(0xd83ddc17L, new Integer[]{832,1408});
        offsets.put(0xd83ddc3dL, new Integer[]{320,1472});
        offsets.put(0xd83ddc0fL, new Integer[]{320,1408});
        offsets.put(0xd83ddc11L, new Integer[]{448,1408});
        offsets.put(0xd83ddc10L, new Integer[]{384,1408});
        offsets.put(0xd83ddc2aL, new Integer[]{1472,576});
        offsets.put(0xd83ddc2bL, new Integer[]{1472,640});
        offsets.put(0xd83ddc18L, new Integer[]{896,1408});
        offsets.put(0xd83ddc2dL, new Integer[]{1472,768});
        offsets.put(0xd83ddc01L, new Integer[]{1408,832});
        offsets.put(0xd83ddc00L, new Integer[]{1408,768});
        offsets.put(0xd83ddc39L, new Integer[]{64,1472});
        offsets.put(0xd83ddc30L, new Integer[]{1472,960});
        offsets.put(0xd83ddc07L, new Integer[]{1408,1216});
        offsets.put(0xd83ddc3fL, new Integer[]{448,1472});
        offsets.put(0xd83ddc3bL, new Integer[]{192,1472});
        offsets.put(0xd83ddc28L, new Integer[]{1472,448});
        offsets.put(0xd83ddc3cL, new Integer[]{256,1472});
        offsets.put(0xd83ddc3eL, new Integer[]{384,1472});
        offsets.put(0xd83ddc14L, new Integer[]{640,1408});
        offsets.put(0xd83ddc13L, new Integer[]{576,1408});
        offsets.put(0xd83ddc23L, new Integer[]{1472,128});
        offsets.put(0xd83ddc24L, new Integer[]{1472,192});
        offsets.put(0xd83ddc25L, new Integer[]{1472,256});
        offsets.put(0xd83ddc26L, new Integer[]{1472,320});
        offsets.put(0xd83ddc27L, new Integer[]{1472,384});
        offsets.put(0xd83ddd4aL, new Integer[]{1472,1792});
        offsets.put(0xd83ddc38L, new Integer[]{0,1472});
        offsets.put(0xd83ddc0aL, new Integer[]{0,1408});
        offsets.put(0xd83ddc22L, new Integer[]{1472,64});
        offsets.put(0xd83ddc0dL, new Integer[]{192,1408});
        offsets.put(0xd83ddc32L, new Integer[]{1472,1088});
        offsets.put(0xd83ddc09L, new Integer[]{1408,1344});
        offsets.put(0xd83ddc33L, new Integer[]{1472,1152});
        offsets.put(0xd83ddc0bL, new Integer[]{64,1408});
        offsets.put(0xd83ddc2cL, new Integer[]{1472,704});
        offsets.put(0xd83ddc1fL, new Integer[]{1344,1408});
        offsets.put(0xd83ddc20L, new Integer[]{1408,1408});
        offsets.put(0xd83ddc21L, new Integer[]{1472,0});
        offsets.put(0xd83ddc19L, new Integer[]{960,1408});
        offsets.put(0xd83ddc1aL, new Integer[]{1024,1408});
        offsets.put(0xd83ddc0cL, new Integer[]{128,1408});
        offsets.put(0xd83ddc1bL, new Integer[]{1088,1408});
        offsets.put(0xd83ddc1cL, new Integer[]{1152,1408});
        offsets.put(0xd83ddc1dL, new Integer[]{1216,1408});
        offsets.put(0xd83ddc1eL, new Integer[]{1280,1408});
        offsets.put(0xd83ddd77L, new Integer[]{320,1856});
        offsets.put(0xd83ddd78L, new Integer[]{384,1856});
        offsets.put(0xd83ddc90L, new Integer[]{512,1600});
        offsets.put(0xd83cdf38L, new Integer[]{320,1088});
        offsets.put(0xd83ddcaeL, new Integer[]{1664,768});
        offsets.put(0xd83cdff5L, new Integer[]{1408,576});
        offsets.put(0xd83cdf39L, new Integer[]{384,1088});
        offsets.put(0xd83cdf3aL, new Integer[]{448,1088});
        offsets.put(0xd83cdf3bL, new Integer[]{512,1088});
        offsets.put(0xd83cdf3cL, new Integer[]{576,1088});
        offsets.put(0xd83cdf37L, new Integer[]{256,1088});
        offsets.put(0xd83cdf31L, new Integer[]{1088,960});
        offsets.put(0xd83cdf32L, new Integer[]{1088,1024});
        offsets.put(0xd83cdf33L, new Integer[]{0,1088});
        offsets.put(0xd83cdf34L, new Integer[]{64,1088});
        offsets.put(0xd83cdf35L, new Integer[]{128,1088});
        offsets.put(0xd83cdf3eL, new Integer[]{704,1088});
        offsets.put(0xd83cdf3fL, new Integer[]{768,1088});
        offsets.put(0xd83cdf40L, new Integer[]{832,1088});
        offsets.put(0xd83cdf41L, new Integer[]{896,1088});
        offsets.put(0xd83cdf42L, new Integer[]{960,1088});
        offsets.put(0xd83cdf43L, new Integer[]{1024,1088});
        offsets.put(0xd83cdf0dL, new Integer[]{256,1024});
        offsets.put(0xd83cdf0eL, new Integer[]{320,1024});
        offsets.put(0xd83cdf0fL, new Integer[]{384,1024});
        offsets.put(0xd83cdf10L, new Integer[]{448,1024});
        offsets.put(0xd83cdfd4L, new Integer[]{1344,1216});
        offsets.put(0xd83cdf0bL, new Integer[]{128,1024});
        offsets.put(0xd83dddfbL, new Integer[]{1984,384});
        offsets.put(0xd83dddfeL, new Integer[]{1984,576});
        offsets.put(0xd83cdf04L, new Integer[]{1024,704});
        offsets.put(0xd83cdf05L, new Integer[]{1024,768});
        offsets.put(0xd83cdf0aL, new Integer[]{64,1024});
        offsets.put(0xd83cdf0cL, new Integer[]{192,1024});
        offsets.put(0xd83cdf11L, new Integer[]{512,1024});
        offsets.put(0xd83cdf12L, new Integer[]{576,1024});
        offsets.put(0xd83cdf13L, new Integer[]{640,1024});
        offsets.put(0xd83cdf14L, new Integer[]{704,1024});
        offsets.put(0xd83cdf15L, new Integer[]{768,1024});
        offsets.put(0xd83cdf16L, new Integer[]{832,1024});
        offsets.put(0xd83cdf17L, new Integer[]{896,1024});
        offsets.put(0xd83cdf18L, new Integer[]{960,1024});
        offsets.put(0xd83cdf19L, new Integer[]{1024,1024});
        offsets.put(0xd83cdf1aL, new Integer[]{1088,0});
        offsets.put(0xd83cdf1bL, new Integer[]{1088,64});
        offsets.put(0xd83cdf1cL, new Integer[]{1088,128});
        offsets.put(0x2600L, new Integer[]{2176,1280});
        offsets.put(0xd83cdf1dL, new Integer[]{1088,192});
        offsets.put(0xd83cdf1eL, new Integer[]{1088,256});
        offsets.put(0x2601L, new Integer[]{2176,1344});
        offsets.put(0x26C5L, new Integer[]{1344,2176});
        offsets.put(0xd83cdf28L, new Integer[]{1088,576});
        offsets.put(0xd83cdf08L, new Integer[]{1024,960});
        offsets.put(0x2614L, new Integer[]{2176,1536});
        offsets.put(0x2744L, new Integer[]{2240,576});
        offsets.put(0xd83cdf1fL, new Integer[]{1088,320});
        offsets.put(0xd83cdf20L, new Integer[]{1088,384});
        offsets.put(0xd83ddd25L, new Integer[]{1792,1408});
        offsets.put(0x26A1L, new Integer[]{960,2176});
        offsets.put(0x2B50L, new Integer[]{2240,1984});
        offsets.put(0xd83cdf47L, new Integer[]{1152,128});
        offsets.put(0xd83cdf48L, new Integer[]{1152,192});
        offsets.put(0xd83cdf49L, new Integer[]{1152,256});
        offsets.put(0xd83cdf4aL, new Integer[]{1152,320});
        offsets.put(0xd83cdf4bL, new Integer[]{1152,384});
        offsets.put(0xd83cdf4cL, new Integer[]{1152,448});
        offsets.put(0xd83cdf4dL, new Integer[]{1152,512});
        offsets.put(0xd83cdf4eL, new Integer[]{1152,576});
        offsets.put(0xd83cdf4fL, new Integer[]{1152,640});
        offsets.put(0xd83cdf50L, new Integer[]{1152,704});
        offsets.put(0xd83cdf51L, new Integer[]{1152,768});
        offsets.put(0xd83cdf52L, new Integer[]{1152,832});
        offsets.put(0xd83cdf53L, new Integer[]{1152,896});
        offsets.put(0xd83cdf45L, new Integer[]{1152,0});
        offsets.put(0xd83cdf46L, new Integer[]{1152,64});
        offsets.put(0xd83cdf3dL, new Integer[]{640,1088});
        offsets.put(0xd83cdf36L, new Integer[]{192,1088});
        offsets.put(0xd83cdf44L, new Integer[]{1088,1088});
        offsets.put(0xd83cdf30L, new Integer[]{1088,896});
        offsets.put(0xd83cdf5eL, new Integer[]{448,1152});
        offsets.put(0xd83cdf56L, new Integer[]{1152,1088});
        offsets.put(0xd83cdf57L, new Integer[]{0,1152});
        offsets.put(0xd83cdf54L, new Integer[]{1152,960});
        offsets.put(0xd83cdf5fL, new Integer[]{512,1152});
        offsets.put(0xd83cdf55L, new Integer[]{1152,1024});
        offsets.put(0xd83cdf72L, new Integer[]{1216,512});
        offsets.put(0xd83cdf71L, new Integer[]{1216,448});
        offsets.put(0xd83cdf58L, new Integer[]{64,1152});
        offsets.put(0xd83cdf59L, new Integer[]{128,1152});
        offsets.put(0xd83cdf5aL, new Integer[]{192,1152});
        offsets.put(0xd83cdf5bL, new Integer[]{256,1152});
        offsets.put(0xd83cdf5cL, new Integer[]{320,1152});
        offsets.put(0xd83cdf5dL, new Integer[]{384,1152});
        offsets.put(0xd83cdf60L, new Integer[]{576,1152});
        offsets.put(0xd83cdf62L, new Integer[]{704,1152});
        offsets.put(0xd83cdf63L, new Integer[]{768,1152});
        offsets.put(0xd83cdf64L, new Integer[]{832,1152});
        offsets.put(0xd83cdf65L, new Integer[]{896,1152});
        offsets.put(0xd83cdf61L, new Integer[]{640,1152});
        offsets.put(0xd83cdf66L, new Integer[]{960,1152});
        offsets.put(0xd83cdf67L, new Integer[]{1024,1152});
        offsets.put(0xd83cdf68L, new Integer[]{1088,1152});
        offsets.put(0xd83cdf69L, new Integer[]{1152,1152});
        offsets.put(0xd83cdf6aL, new Integer[]{1216,0});
        offsets.put(0xd83cdf82L, new Integer[]{192,1216});
        offsets.put(0xd83cdf70L, new Integer[]{1216,384});
        offsets.put(0xd83cdf6bL, new Integer[]{1216,64});
        offsets.put(0xd83cdf6cL, new Integer[]{1216,128});
        offsets.put(0xd83cdf6dL, new Integer[]{1216,192});
        offsets.put(0xd83cdf6eL, new Integer[]{1216,256});
        offsets.put(0xd83cdf6fL, new Integer[]{1216,320});
        offsets.put(0xd83cdf7cL, new Integer[]{1216,1152});
        offsets.put(0x2615L, new Integer[]{2176,1600});
        offsets.put(0xd83cdf75L, new Integer[]{1216,704});
        offsets.put(0xd83cdf76L, new Integer[]{1216,768});
        offsets.put(0xd83cdf77L, new Integer[]{1216,832});
        offsets.put(0xd83cdf78L, new Integer[]{1216,896});
        offsets.put(0xd83cdf79L, new Integer[]{1216,960});
        offsets.put(0xd83cdf7aL, new Integer[]{1216,1024});
        offsets.put(0xd83cdf7bL, new Integer[]{1216,1088});
        offsets.put(0xd83cdf7dL, new Integer[]{0,1216});
        offsets.put(0xd83cdf74L, new Integer[]{1216,640});
        offsets.put(0xd83cdf73L, new Integer[]{1216,576});
        offsets.put(0xd83ddc98L, new Integer[]{1024,1600});
        offsets.put(0x2764L, new Integer[]{2240,1088});
        offsets.put(0xd83ddc93L, new Integer[]{704,1600});
        offsets.put(0xd83ddc94L, new Integer[]{768,1600});
        offsets.put(0xd83ddc95L, new Integer[]{832,1600});
        offsets.put(0xd83ddc96L, new Integer[]{896,1600});
        offsets.put(0xd83ddc97L, new Integer[]{960,1600});
        offsets.put(0xd83ddc99L, new Integer[]{1088,1600});
        offsets.put(0xd83ddc9aL, new Integer[]{1152,1600});
        offsets.put(0xd83ddc9bL, new Integer[]{1216,1600});
        offsets.put(0xd83ddc9cL, new Integer[]{1280,1600});
        offsets.put(0xd83ddc9dL, new Integer[]{1344,1600});
        offsets.put(0xd83ddc9eL, new Integer[]{1408,1600});
        offsets.put(0xd83ddc9fL, new Integer[]{1472,1600});
        offsets.put(0xd83ddc8cL, new Integer[]{256,1600});
        offsets.put(0xd83ddca5L, new Integer[]{1664,192});
        offsets.put(0xd83ddcabL, new Integer[]{1664,576});
        offsets.put(0xd83ddc51L, new Integer[]{1536,64});
        offsets.put(0xd83ddc8dL, new Integer[]{320,1600});
        offsets.put(0xd83cdf82L, new Integer[]{192,1216});
        offsets.put(0xd83cdf83L, new Integer[]{256,1216});
        offsets.put(0xd83cdf84L, new Integer[]{320,1216});
        offsets.put(0xd83cdf86L, new Integer[]{448,1216});
        offsets.put(0xd83cdf87L, new Integer[]{512,1216});
        offsets.put(0xd83cdf88L, new Integer[]{576,1216});
        offsets.put(0xd83cdf89L, new Integer[]{640,1216});
        offsets.put(0xd83cdf8aL, new Integer[]{704,1216});
        offsets.put(0xd83cdf8bL, new Integer[]{768,1216});
        offsets.put(0xd83cdf8cL, new Integer[]{832,1216});
        offsets.put(0xd83cdf8dL, new Integer[]{896,1216});
        offsets.put(0xd83cdf8eL, new Integer[]{960,1216});
        offsets.put(0xd83cdf8fL, new Integer[]{1024,1216});
        offsets.put(0xd83cdf90L, new Integer[]{1088,1216});
        offsets.put(0xd83cdf91L, new Integer[]{1152,1216});
        offsets.put(0xd83cdf93L, new Integer[]{1280,0});
        offsets.put(0xd83cdf80L, new Integer[]{64,1216});
        offsets.put(0xd83cdf81L, new Integer[]{128,1216});
        offsets.put(0xd83cdfeeL, new Integer[]{1408,128});
        offsets.put(0xd83ddeb6L, new Integer[]{2112,960});
        offsets.put(0xd83cdfc3L, new Integer[]{1344,448});
        offsets.put(0xd83ddc83L, new Integer[]{1600,1280});
        offsets.put(0xd83cdfa9L, new Integer[]{128,1280});
        offsets.put(0x26FAL, new Integer[]{1792,2176});
        offsets.put(0xd83cdfa0L, new Integer[]{1280,832});
        offsets.put(0xd83cdfa1L, new Integer[]{1280,896});
        offsets.put(0xd83cdfa2L, new Integer[]{1280,960});
        offsets.put(0xd83cdfaaL, new Integer[]{192,1280});
        offsets.put(0xd83cdfadL, new Integer[]{384,1280});
        offsets.put(0xd83cdfa8L, new Integer[]{64,1280});
        offsets.put(0xd83cdfb0L, new Integer[]{576,1280});
        offsets.put(0xd83ddea3L, new Integer[]{1856,2048});
        offsets.put(0xd83ddec0L, new Integer[]{2112,1600});
        offsets.put(0x26C4L, new Integer[]{1280,2176});
        offsets.put(0xd83cdfafL, new Integer[]{512,1280});
        offsets.put(0xd83cdfb4L, new Integer[]{832,1280});
        offsets.put(0xd83cdfabL, new Integer[]{256,1280});
        offsets.put(0x26BDL, new Integer[]{1152,2176});
        offsets.put(0x26BEL, new Integer[]{1216,2176});
        offsets.put(0xd83cdfc0L, new Integer[]{1344,256});
        offsets.put(0xd83cdfc8L, new Integer[]{1344,768});
        offsets.put(0xd83cdfc9L, new Integer[]{1344,832});
        offsets.put(0xd83cdfbeL, new Integer[]{1344,128});
        offsets.put(0xd83cdfb1L, new Integer[]{640,1280});
        offsets.put(0xd83cdfb3L, new Integer[]{768,1280});
        offsets.put(0x26F3L, new Integer[]{1664,2176});
        offsets.put(0xd83cdfccL, new Integer[]{1344,1024});
        offsets.put(0xd83cdfa3L, new Integer[]{1280,1024});
        offsets.put(0xd83cdfbdL, new Integer[]{1344,64});
        offsets.put(0xd83cdfbfL, new Integer[]{1344,192});
        offsets.put(0xd83cdfc2L, new Integer[]{1344,384});
        offsets.put(0xd83cdfc4L, new Integer[]{1344,512});
        offsets.put(0xd83cdfc7L, new Integer[]{1344,704});
        offsets.put(0xd83cdfcaL, new Integer[]{1344,896});
        offsets.put(0xd83cdfcbL, new Integer[]{1344,960});
        offsets.put(0xd83ddeb4L, new Integer[]{2112,832});
        offsets.put(0xd83ddeb5L, new Integer[]{2112,896});
        offsets.put(0xd83cdfceL, new Integer[]{1344,1152});
        offsets.put(0xd83cdfcdL, new Integer[]{1344,1088});
        offsets.put(0xd83cdfc6L, new Integer[]{1344,640});
        offsets.put(0xd83cdfaeL, new Integer[]{448,1280});
        offsets.put(0xd83cdfb2L, new Integer[]{704,1280});
        offsets.put(0xd83cdccfL, new Integer[]{128,192});
        offsets.put(0xd83cdc04L, new Integer[]{64,192});
        offsets.put(0xd83cdfbcL, new Integer[]{1344,0});
        offsets.put(0xd83cdfb5L, new Integer[]{896,1280});
        offsets.put(0xd83cdfb6L, new Integer[]{960,1280});
        offsets.put(0xd83cdfa4L, new Integer[]{1280,1088});
        offsets.put(0xd83cdfa7L, new Integer[]{0,1280});
        offsets.put(0xd83cdfb7L, new Integer[]{1024,1280});
        offsets.put(0xd83cdfb8L, new Integer[]{1088,1280});
        offsets.put(0xd83cdfb9L, new Integer[]{1152,1280});
        offsets.put(0xd83cdfbaL, new Integer[]{1216,1280});
        offsets.put(0xd83cdfbbL, new Integer[]{1280,1280});
        offsets.put(0xd83cdfacL, new Integer[]{320,1280});
        offsets.put(0xd83cdfc1L, new Integer[]{1344,320});
        offsets.put(0xd83cdfe0L, new Integer[]{640,1344});
        offsets.put(0x26EAL, new Integer[]{1536,2176});
        offsets.put(0xd83cdfe2L, new Integer[]{768,1344});
        offsets.put(0xd83cdfe3L, new Integer[]{832,1344});
        offsets.put(0xd83cdfe4L, new Integer[]{896,1344});
        offsets.put(0xd83cdfe5L, new Integer[]{960,1344});
        offsets.put(0xd83cdfe6L, new Integer[]{1024,1344});
        offsets.put(0xd83cdfe8L, new Integer[]{1152,1344});
        offsets.put(0xd83cdfe9L, new Integer[]{1216,1344});
        offsets.put(0xd83cdfeaL, new Integer[]{1280,1344});
        offsets.put(0xd83cdfebL, new Integer[]{1344,1344});
        offsets.put(0xd83cdfecL, new Integer[]{1408,0});
        offsets.put(0xd83cdfedL, new Integer[]{1408,64});
        offsets.put(0xd83cdfefL, new Integer[]{1408,192});
        offsets.put(0xd83cdff0L, new Integer[]{1408,256});
        offsets.put(0xd83ddc92L, new Integer[]{640,1600});
        offsets.put(0xd83dddfcL, new Integer[]{1984,448});
        offsets.put(0xd83dddfdL, new Integer[]{1984,512});
        offsets.put(0x26F2L, new Integer[]{1600,2176});
        offsets.put(0xd83cdf01L, new Integer[]{1024,512});
        offsets.put(0xd83cdf03L, new Integer[]{1024,640});
        offsets.put(0xd83cdf06L, new Integer[]{1024,832});
        offsets.put(0xd83cdf07L, new Integer[]{1024,896});
        offsets.put(0xd83cdf09L, new Integer[]{0,1024});
        offsets.put(0xd83dddffL, new Integer[]{1984,640});
        offsets.put(0xd83dde82L, new Integer[]{2048,1792});
        offsets.put(0xd83dde83L, new Integer[]{2048,1856});
        offsets.put(0xd83dde84L, new Integer[]{2048,1920});
        offsets.put(0xd83dde85L, new Integer[]{2048,1984});
        offsets.put(0xd83dde86L, new Integer[]{0,2048});
        offsets.put(0xd83dde87L, new Integer[]{64,2048});
        offsets.put(0xd83dde88L, new Integer[]{128,2048});
        offsets.put(0xd83dde89L, new Integer[]{192,2048});
        offsets.put(0xd83dde8aL, new Integer[]{256,2048});
        offsets.put(0xd83dde9dL, new Integer[]{1472,2048});
        offsets.put(0xd83dde9eL, new Integer[]{1536,2048});
        offsets.put(0xd83dde8bL, new Integer[]{320,2048});
        offsets.put(0xd83dde8cL, new Integer[]{384,2048});
        offsets.put(0xd83dde8dL, new Integer[]{448,2048});
        offsets.put(0xd83dde8eL, new Integer[]{512,2048});
        offsets.put(0xd83dde8fL, new Integer[]{576,2048});
        offsets.put(0xd83dde90L, new Integer[]{640,2048});
        offsets.put(0xd83dde91L, new Integer[]{704,2048});
        offsets.put(0xd83dde92L, new Integer[]{768,2048});
        offsets.put(0xd83dde93L, new Integer[]{832,2048});
        offsets.put(0xd83dde94L, new Integer[]{896,2048});
        offsets.put(0xd83dde95L, new Integer[]{960,2048});
        offsets.put(0xd83dde96L, new Integer[]{1024,2048});
        offsets.put(0xd83dde97L, new Integer[]{1088,2048});
        offsets.put(0xd83dde98L, new Integer[]{1152,2048});
        offsets.put(0xd83dde9aL, new Integer[]{1280,2048});
        offsets.put(0xd83dde9bL, new Integer[]{1344,2048});
        offsets.put(0xd83dde9cL, new Integer[]{1408,2048});
        offsets.put(0xd83ddeb2L, new Integer[]{2112,704});
        offsets.put(0x26FDL, new Integer[]{1856,2176});
        offsets.put(0xd83ddee4L, new Integer[]{768,2112});
        offsets.put(0xd83ddea8L, new Integer[]{2112,64});
        offsets.put(0x2693L, new Integer[]{832,2176});
        offsets.put(0x26F5L, new Integer[]{1728,2176});
        offsets.put(0xd83ddea3L, new Integer[]{1856,2048});
        offsets.put(0xd83ddea4L, new Integer[]{1920,2048});
        offsets.put(0xd83ddee5L, new Integer[]{832,2112});
        offsets.put(0xd83ddea2L, new Integer[]{1792,2048});
        offsets.put(0x2708L, new Integer[]{2048,2176});
        offsets.put(0xd83ddcbaL, new Integer[]{1664,1536});
        offsets.put(0xd83dde81L, new Integer[]{2048,1728});
        offsets.put(0xd83dde9fL, new Integer[]{1600,2048});
        offsets.put(0xd83ddea0L, new Integer[]{1664,2048});
        offsets.put(0xd83ddea1L, new Integer[]{1728,2048});
        offsets.put(0xd83dde80L, new Integer[]{2048,1664});
        offsets.put(0xd83ddea5L, new Integer[]{1984,2048});
        offsets.put(0xd83ddea6L, new Integer[]{2048,2048});
        offsets.put(0xd83ddea7L, new Integer[]{2112,0});
        offsets.put(0xd83ddec2L, new Integer[]{2112,1728});
        offsets.put(0xd83ddec3L, new Integer[]{2112,1792});
        offsets.put(0xd83ddec4L, new Integer[]{2112,1856});
        offsets.put(0xd83ddec5L, new Integer[]{2112,1920});
        offsets.put(0xd83ddcb4L, new Integer[]{1664,1152});
        offsets.put(0xd83ddcb5L, new Integer[]{1664,1216});
        offsets.put(0xd83ddcb6L, new Integer[]{1664,1280});
        offsets.put(0xd83ddcb7L, new Integer[]{1664,1344});
        offsets.put(0xd83cdde6d83cddebL, new Integer[]{192,320});
        offsets.put(0xd83cdde6d83cddf1L, new Integer[]{384,0});
        offsets.put(0xd83cdde9d83cddffL, new Integer[]{576,64});
        offsets.put(0xd83cdde6d83cdde9L, new Integer[]{64,320});
        offsets.put(0xd83cdde6d83cddf4L, new Integer[]{384,128});
        offsets.put(0xd83cdde6d83cddeeL, new Integer[]{320,320});
        offsets.put(0xd83cdde6d83cddecL, new Integer[]{256,320});
        offsets.put(0xd83cdde6d83cddf7L, new Integer[]{384,192});
        offsets.put(0xd83cdde6d83cddf2L, new Integer[]{384,64});
        offsets.put(0xd83cdde6d83cddfcL, new Integer[]{0,384});
        offsets.put(0xd83cdde6d83cdde8L, new Integer[]{0,320});
        offsets.put(0xd83cdde6d83cddfaL, new Integer[]{384,320});
        offsets.put(0xd83cdde6d83cddf9L, new Integer[]{384,256});
        offsets.put(0xd83cdde6d83cddffL, new Integer[]{64,384});
        offsets.put(0xd83cdde7d83cddf8L, new Integer[]{64,448});
        offsets.put(0xd83cdde7d83cddedL, new Integer[]{448,64});
        offsets.put(0xd83cdde7d83cdde9L, new Integer[]{256,384});
        offsets.put(0xd83cdde7d83cdde7L, new Integer[]{192,384});
        offsets.put(0xd83cdde7d83cddfeL, new Integer[]{256,448});
        offsets.put(0xd83cdde7d83cddeaL, new Integer[]{320,384});
        offsets.put(0xd83cdde7d83cddffL, new Integer[]{320,448});
        offsets.put(0xd83cdde7d83cddefL, new Integer[]{448,192});
        offsets.put(0xd83cdde7d83cddf2L, new Integer[]{448,256});
        offsets.put(0xd83cdde7d83cddf9L, new Integer[]{128,448});
        offsets.put(0xd83cdde7d83cddf4L, new Integer[]{448,384});
        offsets.put(0xd83cdde7d83cdde6L, new Integer[]{128,384});
        offsets.put(0xd83cdde7d83cddfcL, new Integer[]{192,448});
        offsets.put(0xd83cdde7d83cddf7L, new Integer[]{0,448});
        offsets.put(0xd83cdde7d83cddf3L, new Integer[]{448,320});
        offsets.put(0xd83cdde7d83cddecL, new Integer[]{448,0});
        offsets.put(0xd83cdde7d83cddebL, new Integer[]{384,384});
        offsets.put(0xd83cdde7d83cddeeL, new Integer[]{448,128});
        offsets.put(0xd83cddf0d83cddedL, new Integer[]{704,576});
        offsets.put(0xd83cdde8d83cddf2L, new Integer[]{512,320});
        offsets.put(0xd83cdde8d83cdde6L, new Integer[]{384,448});
        offsets.put(0xd83cdde8d83cddfbL, new Integer[]{128,512});
        offsets.put(0xd83cddf0d83cddfeL, new Integer[]{320,704});
        offsets.put(0xd83cdde8d83cddebL, new Integer[]{512,0});
        offsets.put(0xd83cddf9d83cdde9L, new Integer[]{448,896});
        offsets.put(0xd83cdde8d83cddf1L, new Integer[]{512,256});
        offsets.put(0xd83cdde8d83cddf3L, new Integer[]{512,384});
        offsets.put(0xd83cdde8d83cddf4L, new Integer[]{512,448});
        offsets.put(0xd83cddf0d83cddf2L, new Integer[]{0,704});
        offsets.put(0xd83cdde8d83cddecL, new Integer[]{512,64});
        offsets.put(0xd83cdde8d83cdde9L, new Integer[]{448,448});
        offsets.put(0xd83cdde8d83cddf7L, new Integer[]{0,512});
        offsets.put(0xd83cdde8d83cddeeL, new Integer[]{512,192});
        offsets.put(0xd83cddedd83cddf7L, new Integer[]{192,640});
        offsets.put(0xd83cdde8d83cddfaL, new Integer[]{64,512});
        offsets.put(0xd83cdde8d83cddfeL, new Integer[]{192,512});
        offsets.put(0xd83cdde8d83cddffL, new Integer[]{256,512});
        offsets.put(0xd83cdde9d83cddf0L, new Integer[]{448,512});
        offsets.put(0xd83cdde9d83cddefL, new Integer[]{384,512});
        offsets.put(0xd83cdde9d83cddf2L, new Integer[]{512,512});
        offsets.put(0xd83cdde9d83cddf4L, new Integer[]{576,0});
        offsets.put(0xd83cddead83cdde8L, new Integer[]{576,128});
        offsets.put(0xd83cddead83cddecL, new Integer[]{576,256});
        offsets.put(0xd83cddf8d83cddfbL, new Integer[]{256,896});
        offsets.put(0xd83cddecd83cddf6L, new Integer[]{640,320});
        offsets.put(0xd83cddead83cddf7L, new Integer[]{576,384});
        offsets.put(0xd83cddead83cddeaL, new Integer[]{576,192});
        offsets.put(0xd83cddead83cddf9L, new Integer[]{576,512});
        offsets.put(0xd83cddebd83cddf0L, new Integer[]{128,576});
        offsets.put(0xd83cddebd83cddf4L, new Integer[]{256,576});
        offsets.put(0xd83cddebd83cddefL, new Integer[]{64,576});
        offsets.put(0xd83cddebd83cddeeL, new Integer[]{0,576});
        offsets.put(0xd83cddebd83cddf7L, new Integer[]{320,576});
        offsets.put(0xd83cddf5d83cddebL, new Integer[]{128,832});
        offsets.put(0xd83cddecd83cdde6L, new Integer[]{384,576});
        offsets.put(0xd83cddecd83cddf2L, new Integer[]{640,192});
        offsets.put(0xd83cddecd83cddeaL, new Integer[]{576,576});
        offsets.put(0xd83cdde9d83cddeaL, new Integer[]{320,512});
        offsets.put(0xd83cddecd83cddedL, new Integer[]{640,0});
        offsets.put(0xd83cddecd83cddeeL, new Integer[]{640,64});
        offsets.put(0xd83cddecd83cddf7L, new Integer[]{640,384});
        offsets.put(0xd83cddecd83cddf1L, new Integer[]{640,128});
        offsets.put(0xd83cddecd83cdde9L, new Integer[]{512,576});
        offsets.put(0xd83cddecd83cddfaL, new Integer[]{640,512});
        offsets.put(0xd83cddecd83cddf9L, new Integer[]{640,448});
        offsets.put(0xd83cddecd83cddf3L, new Integer[]{640,256});
        offsets.put(0xd83cddecd83cddfcL, new Integer[]{640,576});
        offsets.put(0xd83cddecd83cddfeL, new Integer[]{0,640});
        offsets.put(0xd83cddedd83cddf9L, new Integer[]{256,640});
        offsets.put(0xd83cddedd83cddf3L, new Integer[]{128,640});
        offsets.put(0xd83cddedd83cddf0L, new Integer[]{64,640});
        offsets.put(0xd83cddedd83cddfaL, new Integer[]{320,640});
        offsets.put(0xd83cddeed83cddf8L, new Integer[]{704,64});
        offsets.put(0xd83cddeed83cddf3L, new Integer[]{576,640});
        offsets.put(0xd83cddeed83cdde9L, new Integer[]{384,640});
        offsets.put(0xd83cddeed83cddf7L, new Integer[]{704,0});
        offsets.put(0xd83cddeed83cddf6L, new Integer[]{640,640});
        offsets.put(0xd83cddeed83cddeaL, new Integer[]{448,640});
        offsets.put(0xd83cddeed83cddf1L, new Integer[]{512,640});
        offsets.put(0xd83cddeed83cddf9L, new Integer[]{704,128});
        offsets.put(0xd83cddefd83cddf2L, new Integer[]{704,256});
        offsets.put(0xd83cddefd83cddf5L, new Integer[]{704,384});
        offsets.put(0xd83cddefd83cddeaL, new Integer[]{704,192});
        offsets.put(0xd83cddefd83cddf4L, new Integer[]{704,320});
        offsets.put(0xd83cddf0d83cddffL, new Integer[]{384,704});
        offsets.put(0xd83cddf0d83cddeaL, new Integer[]{704,448});
        offsets.put(0xd83cddf0d83cddeeL, new Integer[]{704,640});
        offsets.put(0xd83cddfdd83cddf0L, new Integer[]{192,960});
        offsets.put(0xd83cddf0d83cddfcL, new Integer[]{256,704});
        offsets.put(0xd83cddf0d83cddecL, new Integer[]{704,512});
        offsets.put(0xd83cddf1d83cdde6L, new Integer[]{448,704});
        offsets.put(0xd83cddf1d83cddfbL, new Integer[]{768,256});
        offsets.put(0xd83cddf1d83cdde7L, new Integer[]{512,704});
        offsets.put(0xd83cddf1d83cddf8L, new Integer[]{768,64});
        offsets.put(0xd83cddf1d83cddf7L, new Integer[]{768,0});
        offsets.put(0xd83cddf1d83cddfeL, new Integer[]{768,320});
        offsets.put(0xd83cddf1d83cddeeL, new Integer[]{640,704});
        offsets.put(0xd83cddf1d83cddf9L, new Integer[]{768,128});
        offsets.put(0xd83cddf1d83cddfaL, new Integer[]{768,192});
        offsets.put(0xd83cddf2d83cddf4L, new Integer[]{256,768});
        offsets.put(0xd83cddf2d83cddf0L, new Integer[]{0,768});
        offsets.put(0xd83cddf2d83cddecL, new Integer[]{768,640});
        offsets.put(0xd83cddf2d83cddfcL, new Integer[]{640,768});
        offsets.put(0xd83cddf2d83cddfeL, new Integer[]{768,768});
        offsets.put(0xd83cddf2d83cddfbL, new Integer[]{576,768});
        offsets.put(0xd83cddf2d83cddf1L, new Integer[]{64,768});
        offsets.put(0xd83cddf2d83cddf9L, new Integer[]{448,768});
        offsets.put(0xd83cddf2d83cddedL, new Integer[]{768,704});
        offsets.put(0xd83cddf2d83cddf7L, new Integer[]{320,768});
        offsets.put(0xd83cddf2d83cddfaL, new Integer[]{512,768});
        offsets.put(0xd83cddf2d83cddfdL, new Integer[]{704,768});
        offsets.put(0xd83cddebd83cddf2L, new Integer[]{192,576});
        offsets.put(0xd83cddf2d83cdde9L, new Integer[]{768,512});
        offsets.put(0xd83cddf2d83cdde8L, new Integer[]{768,448});
        offsets.put(0xd83cddf2d83cddf3L, new Integer[]{192,768});
        offsets.put(0xd83cddf2d83cddeaL, new Integer[]{768,576});
        offsets.put(0xd83cddf2d83cddf8L, new Integer[]{384,768});
        offsets.put(0xd83cddf2d83cdde6L, new Integer[]{768,384});
        offsets.put(0xd83cddf2d83cddffL, new Integer[]{832,0});
        offsets.put(0xd83cddf2d83cddf2L, new Integer[]{128,768});
        offsets.put(0xd83cddf3d83cdde6L, new Integer[]{832,64});
        offsets.put(0xd83cddf3d83cddf7L, new Integer[]{832,576});
        offsets.put(0xd83cddf3d83cddf5L, new Integer[]{832,512});
        offsets.put(0xd83cddf3d83cddf1L, new Integer[]{832,384});
        offsets.put(0xd83cddf3d83cdde8L, new Integer[]{832,128});
        offsets.put(0xd83cddf3d83cddffL, new Integer[]{832,704});
        offsets.put(0xd83cddf3d83cddeeL, new Integer[]{832,320});
        offsets.put(0xd83cddf3d83cddeaL, new Integer[]{832,192});
        offsets.put(0xd83cddf3d83cddecL, new Integer[]{832,256});
        offsets.put(0xd83cddf3d83cddfaL, new Integer[]{832,640});
        offsets.put(0xd83cddf0d83cddf5L, new Integer[]{128,704});
        offsets.put(0xd83cddf3d83cddf4L, new Integer[]{832,448});
        offsets.put(0xd83cddf4d83cddf2L, new Integer[]{832,768});
        offsets.put(0xd83cddf5d83cddf0L, new Integer[]{320,832});
        offsets.put(0xd83cddf5d83cddfcL, new Integer[]{640,832});
        offsets.put(0xd83cddf5d83cddf8L, new Integer[]{512,832});
        offsets.put(0xd83cddf5d83cdde6L, new Integer[]{0,832});
        offsets.put(0xd83cddf5d83cddecL, new Integer[]{192,832});
        offsets.put(0xd83cddf5d83cddfeL, new Integer[]{704,832});
        offsets.put(0xd83cddf5d83cddeaL, new Integer[]{64,832});
        offsets.put(0xd83cddf5d83cddedL, new Integer[]{256,832});
        offsets.put(0xd83cddf5d83cddf1L, new Integer[]{384,832});
        offsets.put(0xd83cddf5d83cddf9L, new Integer[]{576,832});
        offsets.put(0xd83cddf5d83cddf7L, new Integer[]{448,832});
        offsets.put(0xd83cddf6d83cdde6L, new Integer[]{768,832});
        offsets.put(0xd83cddf7d83cddf4L, new Integer[]{832,832});
        offsets.put(0xd83cddf7d83cddfaL, new Integer[]{896,64});
        offsets.put(0xd83cddf7d83cddfcL, new Integer[]{896,128});
        offsets.put(0xd83cddfcd83cddf8L, new Integer[]{128,960});
        offsets.put(0xd83cddf8d83cddf2L, new Integer[]{896,832});
        offsets.put(0xd83cddf8d83cddf9L, new Integer[]{192,896});
        offsets.put(0xd83cddf8d83cdde6L, new Integer[]{896,192});
        offsets.put(0xd83cddf8d83cddf3L, new Integer[]{0,896});
        offsets.put(0xd83cddf7d83cddf8L, new Integer[]{896,0});
        offsets.put(0xd83cddf8d83cdde8L, new Integer[]{896,320});
        offsets.put(0xd83cddf8d83cddf1L, new Integer[]{896,768});
        offsets.put(0xd83cddf8d83cddecL, new Integer[]{896,512});
        offsets.put(0xd83cddf8d83cddf0L, new Integer[]{896,704});
        offsets.put(0xd83cddf8d83cddeeL, new Integer[]{896,640});
        offsets.put(0xd83cddf8d83cdde7L, new Integer[]{896,256});
        offsets.put(0xd83cddf8d83cddf4L, new Integer[]{64,896});
        offsets.put(0xd83cddffd83cdde6L, new Integer[]{320,960});
        offsets.put(0xd83cddf0d83cddf7L, new Integer[]{192,704});
        offsets.put(0xd83cddead83cddf8L, new Integer[]{576,448});
        offsets.put(0xd83cddf1d83cddf0L, new Integer[]{704,704});
        offsets.put(0xd83cddf8d83cddedL, new Integer[]{896,576});
        offsets.put(0xd83cddf0d83cddf3L, new Integer[]{64,704});
        offsets.put(0xd83cddf1d83cdde8L, new Integer[]{576,704});
        offsets.put(0xd83cddfbd83cdde8L, new Integer[]{960,704});
        offsets.put(0xd83cddf8d83cdde9L, new Integer[]{896,384});
        offsets.put(0xd83cddf8d83cddf7L, new Integer[]{128,896});
        offsets.put(0xd83cddf8d83cddffL, new Integer[]{384,896});
        offsets.put(0xd83cddf8d83cddeaL, new Integer[]{896,448});
        offsets.put(0xd83cdde8d83cddedL, new Integer[]{512,128});
        offsets.put(0xd83cddf8d83cddfeL, new Integer[]{320,896});
        offsets.put(0xd83cddf9d83cddfcL, new Integer[]{960,192});
        offsets.put(0xd83cddf9d83cddefL, new Integer[]{640,896});
        offsets.put(0xd83cddf9d83cddffL, new Integer[]{960,256});
        offsets.put(0xd83cddf9d83cddedL, new Integer[]{576,896});
        offsets.put(0xd83cddf9d83cddf1L, new Integer[]{704,896});
        offsets.put(0xd83cddf9d83cddecL, new Integer[]{512,896});
        offsets.put(0xd83cddf9d83cddf4L, new Integer[]{896,896});
        offsets.put(0xd83cddf9d83cddf9L, new Integer[]{960,64});
        offsets.put(0xd83cddf9d83cddf3L, new Integer[]{832,896});
        offsets.put(0xd83cddf9d83cddf7L, new Integer[]{960,0});
        offsets.put(0xd83cddf9d83cddf2L, new Integer[]{768,896});
        offsets.put(0xd83cddf9d83cddfbL, new Integer[]{960,128});
        offsets.put(0xd83cddfad83cddecL, new Integer[]{960,384});
        offsets.put(0xd83cddfad83cdde6L, new Integer[]{960,320});
        offsets.put(0xd83cdde6d83cddeaL, new Integer[]{128,320});
        offsets.put(0xd83cddecd83cdde7L, new Integer[]{448,576});
        offsets.put(0xd83cddfad83cddf8L, new Integer[]{960,448});
        offsets.put(0xd83cddfad83cddfeL, new Integer[]{960,512});
        offsets.put(0xd83cddfbd83cddeeL, new Integer[]{960,832});
        offsets.put(0xd83cddfad83cddffL, new Integer[]{960,576});
        offsets.put(0xd83cddfbd83cddfaL, new Integer[]{0,960});
        offsets.put(0xd83cddfbd83cdde6L, new Integer[]{960,640});
        offsets.put(0xd83cddfbd83cddeaL, new Integer[]{960,768});
        offsets.put(0xd83cddfbd83cddf3L, new Integer[]{960,896});
        offsets.put(0xd83cddfcd83cddebL, new Integer[]{64,960});
        offsets.put(0xd83cddead83cddedL, new Integer[]{576,320});
        offsets.put(0xd83cddfed83cddeaL, new Integer[]{256,960});
        offsets.put(0xd83cddffd83cddf2L, new Integer[]{384,960});
        offsets.put(0xd83cddffd83cddfcL, new Integer[]{448,960});
        offsets.put(0xd83ddca4L, new Integer[]{1664,128});
        offsets.put(0xd83ddca2L, new Integer[]{1664,0});
        offsets.put(0xd83ddca3L, new Integer[]{1664,64});
        offsets.put(0xd83ddcacL, new Integer[]{1664,640});
        offsets.put(0xd83ddcadL, new Integer[]{1664,704});
        offsets.put(0xd83ddc53L, new Integer[]{1536,192});
        offsets.put(0xd83ddc54L, new Integer[]{1536,256});
        offsets.put(0xd83ddc55L, new Integer[]{1536,320});
        offsets.put(0xd83ddc56L, new Integer[]{1536,384});
        offsets.put(0xd83ddc57L, new Integer[]{1536,448});
        offsets.put(0xd83ddc58L, new Integer[]{1536,512});
        offsets.put(0xd83ddc59L, new Integer[]{1536,576});
        offsets.put(0xd83ddc5aL, new Integer[]{1536,640});
        offsets.put(0xd83ddc5bL, new Integer[]{1536,704});
        offsets.put(0xd83ddc5cL, new Integer[]{1536,768});
        offsets.put(0xd83ddc5dL, new Integer[]{1536,832});
        offsets.put(0xd83ddecdL, new Integer[]{320,2112});
        offsets.put(0xd83cdf92L, new Integer[]{1216,1216});
        offsets.put(0xd83ddc5eL, new Integer[]{1536,896});
        offsets.put(0xd83ddc5fL, new Integer[]{1536,960});
        offsets.put(0xd83ddc60L, new Integer[]{1536,1024});
        offsets.put(0xd83ddc61L, new Integer[]{1536,1088});
        offsets.put(0xd83ddc62L, new Integer[]{1536,1152});
        offsets.put(0xd83ddc52L, new Integer[]{1536,128});
        offsets.put(0xd83ddc84L, new Integer[]{1600,1344});
        offsets.put(0xd83ddc8eL, new Integer[]{384,1600});
        offsets.put(0xd83ddcaeL, new Integer[]{1664,768});
        offsets.put(0x2668L, new Integer[]{640,2176});
        offsets.put(0xd83ddc88L, new Integer[]{0,1600});
        offsets.put(0xd83ddeb3L, new Integer[]{2112,768});
        offsets.put(0xd83ddd31L, new Integer[]{384,1792});
        offsets.put(0xd83cdfe7L, new Integer[]{1088,1344});
        offsets.put(0xd83ddeaeL, new Integer[]{2112,448});
        offsets.put(0xd83ddeabL, new Integer[]{2112,256});
        offsets.put(0xd83ddeadL, new Integer[]{2112,384});
        offsets.put(0xd83ddeafL, new Integer[]{2112,512});
        offsets.put(0xd83ddeb0L, new Integer[]{2112,576});
        offsets.put(0xd83ddeb1L, new Integer[]{2112,640});
        offsets.put(0xd83ddeb7L, new Integer[]{2112,1024});
        offsets.put(0xd83ddeb8L, new Integer[]{2112,1088});
        offsets.put(0x267FL, new Integer[]{768,2176});
        offsets.put(0xd83ddeb9L, new Integer[]{2112,1152});
        offsets.put(0xd83ddebaL, new Integer[]{2112,1216});
        offsets.put(0xd83ddebbL, new Integer[]{2112,1280});
        offsets.put(0xd83ddebcL, new Integer[]{2112,1344});
        offsets.put(0xd83ddebeL, new Integer[]{2112,1472});
        offsets.put(0x26A0L, new Integer[]{896,2176});
        offsets.put(0x26D4L, new Integer[]{1472,2176});
        offsets.put(0xd83ddeaaL, new Integer[]{2112,192});
        offsets.put(0xd83ddebdL, new Integer[]{2112,1408});
        offsets.put(0xd83ddebfL, new Integer[]{2112,1536});
        offsets.put(0xd83ddec1L, new Integer[]{2112,1664});
        offsets.put(0x231BL, new Integer[]{2176,256});
        offsets.put(0x23F3L, new Integer[]{2176,640});
        offsets.put(0x231AL, new Integer[]{2176,192});
        offsets.put(0x23F0L, new Integer[]{2176,576});
        offsets.put(0xd83ddd5bL, new Integer[]{1856,384});
        offsets.put(0xd83ddd67L, new Integer[]{1856,1152});
        offsets.put(0xd83ddd50L, new Integer[]{1536,1792});
        offsets.put(0xd83ddd5cL, new Integer[]{1856,448});
        offsets.put(0xd83ddd51L, new Integer[]{1600,1792});
        offsets.put(0xd83ddd5dL, new Integer[]{1856,512});
        offsets.put(0xd83ddd52L, new Integer[]{1664,1792});
        offsets.put(0xd83ddd5eL, new Integer[]{1856,576});
        offsets.put(0xd83ddd53L, new Integer[]{1728,1792});
        offsets.put(0xd83ddd5fL, new Integer[]{1856,640});
        offsets.put(0xd83ddd54L, new Integer[]{1792,1792});
        offsets.put(0xd83ddd60L, new Integer[]{1856,704});
        offsets.put(0xd83ddd55L, new Integer[]{1856,0});
        offsets.put(0xd83ddd61L, new Integer[]{1856,768});
        offsets.put(0xd83ddd56L, new Integer[]{1856,64});
        offsets.put(0xd83ddd62L, new Integer[]{1856,832});
        offsets.put(0xd83ddd57L, new Integer[]{1856,128});
        offsets.put(0xd83ddd63L, new Integer[]{1856,896});
        offsets.put(0xd83ddd58L, new Integer[]{1856,192});
        offsets.put(0xd83ddd64L, new Integer[]{1856,960});
        offsets.put(0xd83ddd59L, new Integer[]{1856,256});
        offsets.put(0xd83ddd65L, new Integer[]{1856,1024});
        offsets.put(0xd83ddd5aL, new Integer[]{1856,320});
        offsets.put(0xd83ddd66L, new Integer[]{1856,1088});
        offsets.put(0x2648L, new Integer[]{2176,1792});
        offsets.put(0x2649L, new Integer[]{2176,1856});
        offsets.put(0x264AL, new Integer[]{2176,1920});
        offsets.put(0x264BL, new Integer[]{2176,1984});
        offsets.put(0x264CL, new Integer[]{2176,2048});
        offsets.put(0x264DL, new Integer[]{2176,2112});
        offsets.put(0x264EL, new Integer[]{0,2176});
        offsets.put(0x264FL, new Integer[]{64,2176});
        offsets.put(0x2650L, new Integer[]{128,2176});
        offsets.put(0x2651L, new Integer[]{192,2176});
        offsets.put(0x2652L, new Integer[]{256,2176});
        offsets.put(0x2653L, new Integer[]{320,2176});
        offsets.put(0x26CEL, new Integer[]{1408,2176});
        offsets.put(0xd83cdf00L, new Integer[]{1024,448});
        offsets.put(0xd83cdf02L, new Integer[]{1024,576});
        offsets.put(0x2660L, new Integer[]{384,2176});
        offsets.put(0x2665L, new Integer[]{512,2176});
        offsets.put(0x2666L, new Integer[]{576,2176});
        offsets.put(0x2663L, new Integer[]{448,2176});
        offsets.put(0xd83ddd07L, new Integer[]{1280,1728});
        offsets.put(0xd83ddd08L, new Integer[]{1344,1728});
        offsets.put(0xd83ddd09L, new Integer[]{1408,1728});
        offsets.put(0xd83ddd0aL, new Integer[]{1472,1728});
        offsets.put(0xd83ddce2L, new Integer[]{1728,704});
        offsets.put(0xd83ddce3L, new Integer[]{1728,768});
        offsets.put(0xd83ddcefL, new Integer[]{1728,1536});
        offsets.put(0xd83ddd14L, new Integer[]{1792,320});
        offsets.put(0xd83ddd15L, new Integer[]{1792,384});
        offsets.put(0xd83ddd00L, new Integer[]{832,1728});
        offsets.put(0xd83ddd01L, new Integer[]{896,1728});
        offsets.put(0xd83ddd02L, new Integer[]{960,1728});
        offsets.put(0x25B6L, new Integer[]{2176,896});
        offsets.put(0x23E9L, new Integer[]{2176,320});
        offsets.put(0x25C0L, new Integer[]{2176,960});
        offsets.put(0x23EAL, new Integer[]{2176,384});
        offsets.put(0xd83ddd3cL, new Integer[]{1088,1792});
        offsets.put(0x23EBL, new Integer[]{2176,448});
        offsets.put(0xd83ddd3dL, new Integer[]{1152,1792});
        offsets.put(0x23ECL, new Integer[]{2176,512});
        offsets.put(0xd83ddcfbL, new Integer[]{576,1728});
        offsets.put(0xd83ddcf1L, new Integer[]{1728,1664});
        offsets.put(0xd83ddcf3L, new Integer[]{64,1728});
        offsets.put(0xd83ddcf4L, new Integer[]{128,1728});
        offsets.put(0xd83ddcf2L, new Integer[]{0,1728});
        offsets.put(0xd83ddcf5L, new Integer[]{192,1728});
        offsets.put(0x260EL, new Integer[]{2176,1408});
        offsets.put(0xd83ddcdeL, new Integer[]{1728,448});
        offsets.put(0x002320E3L, new Integer[]{64,0});
        offsets.put(0x003020E3L, new Integer[]{1600,1152});
        offsets.put(0x003120E3L, new Integer[]{0,64});
        offsets.put(0x003220E3L, new Integer[]{64,64});
        offsets.put(0x003320E3L, new Integer[]{128,0});
        offsets.put(0x003420E3L, new Integer[]{128,64});
        offsets.put(0x003520E3L, new Integer[]{0,128});
        offsets.put(0x003620E3L, new Integer[]{64,128});
        offsets.put(0x003720E3L, new Integer[]{128,128});
        offsets.put(0x003820E3L, new Integer[]{192,0});
        offsets.put(0x003920E3L, new Integer[]{192,64});
        offsets.put(0xd83ddd1fL, new Integer[]{1792,1024});
        offsets.put(0xd83ddcf6L, new Integer[]{256,1728});
        offsets.put(0xd83ddcdfL, new Integer[]{1728,512});
        offsets.put(0xd83ddce0L, new Integer[]{1728,576});
        offsets.put(0xd83ddd0bL, new Integer[]{1536,1728});
        offsets.put(0xd83ddd0cL, new Integer[]{1600,1728});
        offsets.put(0xd83ddcbbL, new Integer[]{1664,1600});
        offsets.put(0xd83ddcbdL, new Integer[]{64,1664});
        offsets.put(0xd83ddcbeL, new Integer[]{128,1664});
        offsets.put(0xd83ddcbfL, new Integer[]{192,1664});
        offsets.put(0xd83ddcc0L, new Integer[]{256,1664});
        offsets.put(0xd83cdfa5L, new Integer[]{1280,1152});
        offsets.put(0xd83cdfa6L, new Integer[]{1280,1216});
        offsets.put(0xd83ddcfaL, new Integer[]{512,1728});
        offsets.put(0xd83ddcf7L, new Integer[]{320,1728});
        offsets.put(0xd83ddcfcL, new Integer[]{640,1728});
        offsets.put(0xd83ddd05L, new Integer[]{1152,1728});
        offsets.put(0xd83ddd06L, new Integer[]{1216,1728});
        offsets.put(0xd83ddd0dL, new Integer[]{1664,1728});
        offsets.put(0xd83ddd0eL, new Integer[]{1728,1728});
        offsets.put(0xd83ddd2cL, new Integer[]{64,1792});
        offsets.put(0xd83ddd2dL, new Integer[]{128,1792});
        offsets.put(0xd83ddce1L, new Integer[]{1728,640});
        offsets.put(0xd83ddca1L, new Integer[]{1600,1600});
        offsets.put(0xd83ddd26L, new Integer[]{1792,1472});
        offsets.put(0xd83ddcd4L, new Integer[]{1536,1664});
        offsets.put(0xd83ddcd5L, new Integer[]{1600,1664});
        offsets.put(0xd83ddcd6L, new Integer[]{1664,1664});
        offsets.put(0xd83ddcd7L, new Integer[]{1728,0});
        offsets.put(0xd83ddcd8L, new Integer[]{1728,64});
        offsets.put(0xd83ddcd9L, new Integer[]{1728,128});
        offsets.put(0xd83ddcdaL, new Integer[]{1728,192});
        offsets.put(0xd83ddcd3L, new Integer[]{1472,1664});
        offsets.put(0xd83ddcc3L, new Integer[]{448,1664});
        offsets.put(0xd83ddcdcL, new Integer[]{1728,320});
        offsets.put(0xd83ddcc4L, new Integer[]{512,1664});
        offsets.put(0xd83ddcf0L, new Integer[]{1728,1600});
        offsets.put(0xd83ddcd1L, new Integer[]{1344,1664});
        offsets.put(0xd83ddd16L, new Integer[]{1792,448});
        offsets.put(0xd83ddcb0L, new Integer[]{1664,896});
        offsets.put(0xd83ddcb8L, new Integer[]{1664,1408});
        offsets.put(0xd83ddcb1L, new Integer[]{1664,960});
        offsets.put(0xd83ddcb2L, new Integer[]{1664,1024});
        offsets.put(0xd83ddcb3L, new Integer[]{1664,1088});
        offsets.put(0xd83ddcb9L, new Integer[]{1664,1472});
        offsets.put(0x2709L, new Integer[]{2112,2176});
        offsets.put(0xd83ddce7L, new Integer[]{1728,1024});
        offsets.put(0xd83ddce8L, new Integer[]{1728,1088});
        offsets.put(0xd83ddce9L, new Integer[]{1728,1152});
        offsets.put(0xd83ddce4L, new Integer[]{1728,832});
        offsets.put(0xd83ddce5L, new Integer[]{1728,896});
        offsets.put(0xd83ddce6L, new Integer[]{1728,960});
        offsets.put(0xd83ddcebL, new Integer[]{1728,1280});
        offsets.put(0xd83ddceaL, new Integer[]{1728,1216});
        offsets.put(0xd83ddcecL, new Integer[]{1728,1344});
        offsets.put(0xd83ddcedL, new Integer[]{1728,1408});
        offsets.put(0xd83ddceeL, new Integer[]{1728,1472});
        offsets.put(0x270FL, new Integer[]{2240,128});
        offsets.put(0x2712L, new Integer[]{2240,192});
        offsets.put(0xd83ddcddL, new Integer[]{1728,384});
        offsets.put(0xd83ddcbcL, new Integer[]{0,1664});
        offsets.put(0xd83ddcc1L, new Integer[]{320,1664});
        offsets.put(0xd83ddcc2L, new Integer[]{384,1664});
        offsets.put(0xd83ddcc5L, new Integer[]{576,1664});
        offsets.put(0xd83ddcc6L, new Integer[]{640,1664});
        offsets.put(0xd83ddcc7L, new Integer[]{704,1664});
        offsets.put(0xd83ddcc8L, new Integer[]{768,1664});
        offsets.put(0xd83ddcc9L, new Integer[]{832,1664});
        offsets.put(0xd83ddccaL, new Integer[]{896,1664});
        offsets.put(0xd83ddccbL, new Integer[]{960,1664});
        offsets.put(0xd83ddcccL, new Integer[]{1024,1664});
        offsets.put(0xd83ddccdL, new Integer[]{1088,1664});
        offsets.put(0xd83ddcceL, new Integer[]{1152,1664});
        offsets.put(0xd83ddccfL, new Integer[]{1216,1664});
        offsets.put(0xd83ddcd0L, new Integer[]{1280,1664});
        offsets.put(0xd83ddcdbL, new Integer[]{1728,256});
        offsets.put(0x2702L, new Integer[]{1920,2176});
        offsets.put(0xd83ddd12L, new Integer[]{1792,192});
        offsets.put(0xd83ddd13L, new Integer[]{1792,256});
        offsets.put(0xd83ddd0fL, new Integer[]{1792,0});
        offsets.put(0xd83ddd10L, new Integer[]{1792,64});
        offsets.put(0xd83ddd11L, new Integer[]{1792,128});
        offsets.put(0xd83ddd28L, new Integer[]{1792,1600});
        offsets.put(0xd83ddd27L, new Integer[]{1792,1536});
        offsets.put(0xd83ddd29L, new Integer[]{1792,1664});
        offsets.put(0xd83ddd17L, new Integer[]{1792,512});
        offsets.put(0xd83ddc89L, new Integer[]{64,1600});
        offsets.put(0xd83ddc8aL, new Integer[]{128,1600});
        offsets.put(0xd83ddd2aL, new Integer[]{1792,1728});
        offsets.put(0xd83ddd2bL, new Integer[]{0,1792});
        offsets.put(0xd83ddeacL, new Integer[]{2112,320});
        offsets.put(0xd83ddea9L, new Integer[]{2112,128});
        offsets.put(0x2B06L, new Integer[]{2240,1728});
        offsets.put(0x2197L, new Integer[]{2048,2112});
        offsets.put(0x27A1L, new Integer[]{2240,1344});
        offsets.put(0x2198L, new Integer[]{2112,2112});
        offsets.put(0x2B07L, new Integer[]{2240,1792});
        offsets.put(0x2199L, new Integer[]{2176,0});
        offsets.put(0x2B05L, new Integer[]{2240,1664});
        offsets.put(0x2196L, new Integer[]{1984,2112});
        offsets.put(0x2195L, new Integer[]{1920,2112});
        offsets.put(0x2194L, new Integer[]{1856,2112});
        offsets.put(0x21A9L, new Integer[]{2176,64});
        offsets.put(0x21AAL, new Integer[]{2176,128});
        offsets.put(0x2934L, new Integer[]{2240,1536});
        offsets.put(0x2935L, new Integer[]{2240,1600});
        offsets.put(0xd83ddd03L, new Integer[]{1024,1728});
        offsets.put(0xd83ddd04L, new Integer[]{1088,1728});
        offsets.put(0xd83ddd19L, new Integer[]{1792,640});
        offsets.put(0xd83ddd1aL, new Integer[]{1792,704});
        offsets.put(0xd83ddd1bL, new Integer[]{1792,768});
        offsets.put(0xd83ddd1cL, new Integer[]{1792,832});
        offsets.put(0xd83ddd1dL, new Integer[]{1792,896});
        offsets.put(0xd83ddd30L, new Integer[]{320,1792});
        offsets.put(0xd83ddd2eL, new Integer[]{192,1792});
        offsets.put(0xd83ddd2fL, new Integer[]{256,1792});
        offsets.put(0x267BL, new Integer[]{704,2176});
        offsets.put(0x2B55L, new Integer[]{2240,2048});
        offsets.put(0x2705L, new Integer[]{1984,2176});
        offsets.put(0x2611L, new Integer[]{2176,1472});
        offsets.put(0x2714L, new Integer[]{2240,256});
        offsets.put(0x2716L, new Integer[]{2240,320});
        offsets.put(0x274CL, new Integer[]{2240,704});
        offsets.put(0x274EL, new Integer[]{2240,768});
        offsets.put(0x2795L, new Integer[]{2240,1152});
        offsets.put(0x2796L, new Integer[]{2240,1216});
        offsets.put(0x2797L, new Integer[]{2240,1280});
        offsets.put(0x27B0L, new Integer[]{2240,1408});
        offsets.put(0x27BFL, new Integer[]{2240,1472});
        offsets.put(0x303DL, new Integer[]{2240,2176});
        offsets.put(0x2733L, new Integer[]{2240,448});
        offsets.put(0x2734L, new Integer[]{2240,512});
        offsets.put(0x2747L, new Integer[]{2240,640});
        offsets.put(0x203CL, new Integer[]{1600,2112});
        offsets.put(0x2049L, new Integer[]{1664,2112});
        offsets.put(0x2753L, new Integer[]{2240,832});
        offsets.put(0x2754L, new Integer[]{2240,896});
        offsets.put(0x2755L, new Integer[]{2240,960});
        offsets.put(0x2757L, new Integer[]{2240,1024});
        offsets.put(0x00A9L, new Integer[]{192,128});
        offsets.put(0x00AEL, new Integer[]{0,192});
        offsets.put(0x2122L, new Integer[]{1728,2112});
        offsets.put(0xd83ddcafL, new Integer[]{1664,832});
        offsets.put(0xd83ddd1eL, new Integer[]{1792,960});
        offsets.put(0xd83ddd20L, new Integer[]{1792,1088});
        offsets.put(0xd83ddd21L, new Integer[]{1792,1152});
        offsets.put(0xd83ddd22L, new Integer[]{1792,1216});
        offsets.put(0xd83ddd23L, new Integer[]{1792,1280});
        offsets.put(0xd83ddd24L, new Integer[]{1792,1344});
        offsets.put(0xd83cdd70L, new Integer[]{192,192});
        offsets.put(0xd83cdd8eL, new Integer[]{256,192});
        offsets.put(0xd83cdd71L, new Integer[]{256,0});
        offsets.put(0xd83cdd91L, new Integer[]{0,256});
        offsets.put(0xd83cdd92L, new Integer[]{64,256});
        offsets.put(0xd83cdd93L, new Integer[]{128,256});
        offsets.put(0x2139L, new Integer[]{1792,2112});
        offsets.put(0xd83cdd94L, new Integer[]{192,256});
        offsets.put(0x24C2L, new Integer[]{2176,704});
        offsets.put(0xd83cdd95L, new Integer[]{256,256});
        offsets.put(0xd83cdd96L, new Integer[]{320,0});
        offsets.put(0xd83cdd7eL, new Integer[]{256,64});
        offsets.put(0xd83cdd97L, new Integer[]{320,64});
        offsets.put(0xd83cdd7fL, new Integer[]{256,128});
        offsets.put(0xd83cdd98L, new Integer[]{320,128});
        offsets.put(0xd83cdd99L, new Integer[]{320,192});
        offsets.put(0xd83cdd9aL, new Integer[]{320,256});
        offsets.put(0xd83cde01L, new Integer[]{512,960});
        offsets.put(0xd83cde02L, new Integer[]{576,960});
        offsets.put(0xd83cde37L, new Integer[]{1024,64});
        offsets.put(0xd83cde36L, new Integer[]{1024,0});
        offsets.put(0xd83cde2fL, new Integer[]{704,960});
        offsets.put(0xd83cde50L, new Integer[]{1024,320});
        offsets.put(0xd83cde39L, new Integer[]{1024,192});
        offsets.put(0xd83cde1aL, new Integer[]{640,960});
        offsets.put(0xd83cde32L, new Integer[]{768,960});
        offsets.put(0xd83cde51L, new Integer[]{1024,384});
        offsets.put(0xd83cde38L, new Integer[]{1024,128});
        offsets.put(0xd83cde34L, new Integer[]{896,960});
        offsets.put(0xd83cde33L, new Integer[]{832,960});
        offsets.put(0x3297L, new Integer[]{0,2240});
        offsets.put(0x3299L, new Integer[]{64,2240});
        offsets.put(0xd83cde3aL, new Integer[]{1024,256});
        offsets.put(0xd83cde35L, new Integer[]{960,960});
        offsets.put(0x25AAL, new Integer[]{2176,768});
        offsets.put(0x25ABL, new Integer[]{2176,832});
        offsets.put(0x25FBL, new Integer[]{2176,1024});
        offsets.put(0x25FCL, new Integer[]{2176,1088});
        offsets.put(0x25FDL, new Integer[]{2176,1152});
        offsets.put(0x25FEL, new Integer[]{2176,1216});
        offsets.put(0x2B1BL, new Integer[]{2240,1856});
        offsets.put(0x2B1CL, new Integer[]{2240,1920});
        offsets.put(0xd83ddd36L, new Integer[]{704,1792});
        offsets.put(0xd83ddd37L, new Integer[]{768,1792});
        offsets.put(0xd83ddd38L, new Integer[]{832,1792});
        offsets.put(0xd83ddd39L, new Integer[]{896,1792});
        offsets.put(0xd83ddd3aL, new Integer[]{960,1792});
        offsets.put(0xd83ddd3bL, new Integer[]{1024,1792});
        offsets.put(0xd83ddca0L, new Integer[]{1536,1600});
        offsets.put(0xd83ddd32L, new Integer[]{448,1792});
        offsets.put(0xd83ddd33L, new Integer[]{512,1792});
        offsets.put(0x26AAL, new Integer[]{1024,2176});
        offsets.put(0x26ABL, new Integer[]{1088,2176});
        offsets.put(0xd83ddd34L, new Integer[]{576,1792});
        offsets.put(0xd83ddd35L, new Integer[]{640,1792});
    }
}